/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthOAuth2ConnectorOIDCConfig model module.
 * @module model/AuthOAuth2ConnectorOIDCConfig
 * @version 2.0
 */
class AuthOAuth2ConnectorOIDCConfig {
    /**
     * Constructs a new <code>AuthOAuth2ConnectorOIDCConfig</code>.
     * @alias module:model/AuthOAuth2ConnectorOIDCConfig
     */
    constructor() { 
        
        AuthOAuth2ConnectorOIDCConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthOAuth2ConnectorOIDCConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthOAuth2ConnectorOIDCConfig} obj Optional instance to populate.
     * @return {module:model/AuthOAuth2ConnectorOIDCConfig} The populated <code>AuthOAuth2ConnectorOIDCConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthOAuth2ConnectorOIDCConfig();

            if (data.hasOwnProperty('basicAuthUnsupported')) {
                obj['basicAuthUnsupported'] = ApiClient.convertToType(data['basicAuthUnsupported'], 'Boolean');
            }
            if (data.hasOwnProperty('clientID')) {
                obj['clientID'] = ApiClient.convertToType(data['clientID'], 'String');
            }
            if (data.hasOwnProperty('clientSecret')) {
                obj['clientSecret'] = ApiClient.convertToType(data['clientSecret'], 'String');
            }
            if (data.hasOwnProperty('getUserInfo')) {
                obj['getUserInfo'] = ApiClient.convertToType(data['getUserInfo'], 'Boolean');
            }
            if (data.hasOwnProperty('hostedDomains')) {
                obj['hostedDomains'] = ApiClient.convertToType(data['hostedDomains'], ['String']);
            }
            if (data.hasOwnProperty('insecureSkipEmailVerified')) {
                obj['insecureSkipEmailVerified'] = ApiClient.convertToType(data['insecureSkipEmailVerified'], 'Boolean');
            }
            if (data.hasOwnProperty('issuer')) {
                obj['issuer'] = ApiClient.convertToType(data['issuer'], 'String');
            }
            if (data.hasOwnProperty('redirectURI')) {
                obj['redirectURI'] = ApiClient.convertToType(data['redirectURI'], 'String');
            }
            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], ['String']);
            }
            if (data.hasOwnProperty('userIDKey')) {
                obj['userIDKey'] = ApiClient.convertToType(data['userIDKey'], 'String');
            }
            if (data.hasOwnProperty('userNameKey')) {
                obj['userNameKey'] = ApiClient.convertToType(data['userNameKey'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} basicAuthUnsupported
 */
AuthOAuth2ConnectorOIDCConfig.prototype['basicAuthUnsupported'] = undefined;

/**
 * @member {String} clientID
 */
AuthOAuth2ConnectorOIDCConfig.prototype['clientID'] = undefined;

/**
 * @member {String} clientSecret
 */
AuthOAuth2ConnectorOIDCConfig.prototype['clientSecret'] = undefined;

/**
 * @member {Boolean} getUserInfo
 */
AuthOAuth2ConnectorOIDCConfig.prototype['getUserInfo'] = undefined;

/**
 * @member {Array.<String>} hostedDomains
 */
AuthOAuth2ConnectorOIDCConfig.prototype['hostedDomains'] = undefined;

/**
 * @member {Boolean} insecureSkipEmailVerified
 */
AuthOAuth2ConnectorOIDCConfig.prototype['insecureSkipEmailVerified'] = undefined;

/**
 * @member {String} issuer
 */
AuthOAuth2ConnectorOIDCConfig.prototype['issuer'] = undefined;

/**
 * @member {String} redirectURI
 */
AuthOAuth2ConnectorOIDCConfig.prototype['redirectURI'] = undefined;

/**
 * @member {Array.<String>} scopes
 */
AuthOAuth2ConnectorOIDCConfig.prototype['scopes'] = undefined;

/**
 * @member {String} userIDKey
 */
AuthOAuth2ConnectorOIDCConfig.prototype['userIDKey'] = undefined;

/**
 * @member {String} userNameKey
 */
AuthOAuth2ConnectorOIDCConfig.prototype['userNameKey'] = undefined;






export default AuthOAuth2ConnectorOIDCConfig;

