/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthLdapMapping model module.
 * @module model/AuthLdapMapping
 * @version 2.0
 */
class AuthLdapMapping {
    /**
     * Constructs a new <code>AuthLdapMapping</code>.
     * @alias module:model/AuthLdapMapping
     */
    constructor() { 
        
        AuthLdapMapping.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthLdapMapping</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthLdapMapping} obj Optional instance to populate.
     * @return {module:model/AuthLdapMapping} The populated <code>AuthLdapMapping</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthLdapMapping();

            if (data.hasOwnProperty('LeftAttribute')) {
                obj['LeftAttribute'] = ApiClient.convertToType(data['LeftAttribute'], 'String');
            }
            if (data.hasOwnProperty('RightAttribute')) {
                obj['RightAttribute'] = ApiClient.convertToType(data['RightAttribute'], 'String');
            }
            if (data.hasOwnProperty('RolePrefix')) {
                obj['RolePrefix'] = ApiClient.convertToType(data['RolePrefix'], 'String');
            }
            if (data.hasOwnProperty('RuleString')) {
                obj['RuleString'] = ApiClient.convertToType(data['RuleString'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} LeftAttribute
 */
AuthLdapMapping.prototype['LeftAttribute'] = undefined;

/**
 * @member {String} RightAttribute
 */
AuthLdapMapping.prototype['RightAttribute'] = undefined;

/**
 * @member {String} RolePrefix
 */
AuthLdapMapping.prototype['RolePrefix'] = undefined;

/**
 * @member {String} RuleString
 */
AuthLdapMapping.prototype['RuleString'] = undefined;






export default AuthLdapMapping;

