/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import AuthOAuth2ConnectorGithubConfigOrg from './AuthOAuth2ConnectorGithubConfigOrg';





/**
* The AuthOAuth2ConnectorGithubConfig model module.
* @module model/AuthOAuth2ConnectorGithubConfig
* @version 2.0
*/
export default class AuthOAuth2ConnectorGithubConfig {
    /**
    * Constructs a new <code>AuthOAuth2ConnectorGithubConfig</code>.
    * @alias module:model/AuthOAuth2ConnectorGithubConfig
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AuthOAuth2ConnectorGithubConfig</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthOAuth2ConnectorGithubConfig} obj Optional instance to populate.
    * @return {module:model/AuthOAuth2ConnectorGithubConfig} The populated <code>AuthOAuth2ConnectorGithubConfig</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthOAuth2ConnectorGithubConfig();

            
            
            

            if (data.hasOwnProperty('clientID')) {
                obj['clientID'] = ApiClient.convertToType(data['clientID'], 'String');
            }
            if (data.hasOwnProperty('clientSecret')) {
                obj['clientSecret'] = ApiClient.convertToType(data['clientSecret'], 'String');
            }
            if (data.hasOwnProperty('redirectURI')) {
                obj['redirectURI'] = ApiClient.convertToType(data['redirectURI'], 'String');
            }
            if (data.hasOwnProperty('orgs')) {
                obj['orgs'] = ApiClient.convertToType(data['orgs'], [AuthOAuth2ConnectorGithubConfigOrg]);
            }
            if (data.hasOwnProperty('loadAllGroups')) {
                obj['loadAllGroups'] = ApiClient.convertToType(data['loadAllGroups'], 'Boolean');
            }
            if (data.hasOwnProperty('teamNameField')) {
                obj['teamNameField'] = ApiClient.convertToType(data['teamNameField'], 'String');
            }
            if (data.hasOwnProperty('useLoginAsID')) {
                obj['useLoginAsID'] = ApiClient.convertToType(data['useLoginAsID'], 'Boolean');
            }
            if (data.hasOwnProperty('hostName')) {
                obj['hostName'] = ApiClient.convertToType(data['hostName'], 'String');
            }
            if (data.hasOwnProperty('rootCA')) {
                obj['rootCA'] = ApiClient.convertToType(data['rootCA'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} clientID
    */
    clientID = undefined;
    /**
    * @member {String} clientSecret
    */
    clientSecret = undefined;
    /**
    * @member {String} redirectURI
    */
    redirectURI = undefined;
    /**
    * @member {Array.<module:model/AuthOAuth2ConnectorGithubConfigOrg>} orgs
    */
    orgs = undefined;
    /**
    * @member {Boolean} loadAllGroups
    */
    loadAllGroups = undefined;
    /**
    * @member {String} teamNameField
    */
    teamNameField = undefined;
    /**
    * @member {Boolean} useLoginAsID
    */
    useLoginAsID = undefined;
    /**
    * @member {String} hostName
    */
    hostName = undefined;
    /**
    * @member {String} rootCA
    */
    rootCA = undefined;








}


