/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AuthOAuth2ConnectorOIDCConfig model module.
* @module model/AuthOAuth2ConnectorOIDCConfig
* @version 2.0
*/
export default class AuthOAuth2ConnectorOIDCConfig {
    /**
    * Constructs a new <code>AuthOAuth2ConnectorOIDCConfig</code>.
    * @alias module:model/AuthOAuth2ConnectorOIDCConfig
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AuthOAuth2ConnectorOIDCConfig</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthOAuth2ConnectorOIDCConfig} obj Optional instance to populate.
    * @return {module:model/AuthOAuth2ConnectorOIDCConfig} The populated <code>AuthOAuth2ConnectorOIDCConfig</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthOAuth2ConnectorOIDCConfig();

            
            
            

            if (data.hasOwnProperty('issuer')) {
                obj['issuer'] = ApiClient.convertToType(data['issuer'], 'String');
            }
            if (data.hasOwnProperty('clientID')) {
                obj['clientID'] = ApiClient.convertToType(data['clientID'], 'String');
            }
            if (data.hasOwnProperty('clientSecret')) {
                obj['clientSecret'] = ApiClient.convertToType(data['clientSecret'], 'String');
            }
            if (data.hasOwnProperty('redirectURI')) {
                obj['redirectURI'] = ApiClient.convertToType(data['redirectURI'], 'String');
            }
            if (data.hasOwnProperty('basicAuthUnsupported')) {
                obj['basicAuthUnsupported'] = ApiClient.convertToType(data['basicAuthUnsupported'], 'Boolean');
            }
            if (data.hasOwnProperty('hostedDomains')) {
                obj['hostedDomains'] = ApiClient.convertToType(data['hostedDomains'], ['String']);
            }
            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], ['String']);
            }
            if (data.hasOwnProperty('insecureSkipEmailVerified')) {
                obj['insecureSkipEmailVerified'] = ApiClient.convertToType(data['insecureSkipEmailVerified'], 'Boolean');
            }
            if (data.hasOwnProperty('getUserInfo')) {
                obj['getUserInfo'] = ApiClient.convertToType(data['getUserInfo'], 'Boolean');
            }
            if (data.hasOwnProperty('userIDKey')) {
                obj['userIDKey'] = ApiClient.convertToType(data['userIDKey'], 'String');
            }
            if (data.hasOwnProperty('userNameKey')) {
                obj['userNameKey'] = ApiClient.convertToType(data['userNameKey'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} issuer
    */
    issuer = undefined;
    /**
    * @member {String} clientID
    */
    clientID = undefined;
    /**
    * @member {String} clientSecret
    */
    clientSecret = undefined;
    /**
    * @member {String} redirectURI
    */
    redirectURI = undefined;
    /**
    * @member {Boolean} basicAuthUnsupported
    */
    basicAuthUnsupported = undefined;
    /**
    * @member {Array.<String>} hostedDomains
    */
    hostedDomains = undefined;
    /**
    * @member {Array.<String>} scopes
    */
    scopes = undefined;
    /**
    * @member {Boolean} insecureSkipEmailVerified
    */
    insecureSkipEmailVerified = undefined;
    /**
    * @member {Boolean} getUserInfo
    */
    getUserInfo = undefined;
    /**
    * @member {String} userIDKey
    */
    userIDKey = undefined;
    /**
    * @member {String} userNameKey
    */
    userNameKey = undefined;








}


