/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthLdapSearchFilter model module.
 * @module model/AuthLdapSearchFilter
 * @version 2.0
 */
class AuthLdapSearchFilter {
    /**
     * Constructs a new <code>AuthLdapSearchFilter</code>.
     * @alias module:model/AuthLdapSearchFilter
     */
    constructor() { 
        
        AuthLdapSearchFilter.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthLdapSearchFilter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthLdapSearchFilter} obj Optional instance to populate.
     * @return {module:model/AuthLdapSearchFilter} The populated <code>AuthLdapSearchFilter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthLdapSearchFilter();

            if (data.hasOwnProperty('DNs')) {
                obj['DNs'] = ApiClient.convertToType(data['DNs'], ['String']);
            }
            if (data.hasOwnProperty('DisplayAttribute')) {
                obj['DisplayAttribute'] = ApiClient.convertToType(data['DisplayAttribute'], 'String');
            }
            if (data.hasOwnProperty('Filter')) {
                obj['Filter'] = ApiClient.convertToType(data['Filter'], 'String');
            }
            if (data.hasOwnProperty('IDAttribute')) {
                obj['IDAttribute'] = ApiClient.convertToType(data['IDAttribute'], 'String');
            }
            if (data.hasOwnProperty('Scope')) {
                obj['Scope'] = ApiClient.convertToType(data['Scope'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} DNs
 */
AuthLdapSearchFilter.prototype['DNs'] = undefined;

/**
 * @member {String} DisplayAttribute
 */
AuthLdapSearchFilter.prototype['DisplayAttribute'] = undefined;

/**
 * @member {String} Filter
 */
AuthLdapSearchFilter.prototype['Filter'] = undefined;

/**
 * @member {String} IDAttribute
 */
AuthLdapSearchFilter.prototype['IDAttribute'] = undefined;

/**
 * @member {String} Scope
 */
AuthLdapSearchFilter.prototype['Scope'] = undefined;






export default AuthLdapSearchFilter;

