/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AuthOAuth2ConnectorBitbucketConfig model module.
* @module model/AuthOAuth2ConnectorBitbucketConfig
* @version 2.0
*/
export default class AuthOAuth2ConnectorBitbucketConfig {
    /**
    * Constructs a new <code>AuthOAuth2ConnectorBitbucketConfig</code>.
    * @alias module:model/AuthOAuth2ConnectorBitbucketConfig
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AuthOAuth2ConnectorBitbucketConfig</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthOAuth2ConnectorBitbucketConfig} obj Optional instance to populate.
    * @return {module:model/AuthOAuth2ConnectorBitbucketConfig} The populated <code>AuthOAuth2ConnectorBitbucketConfig</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthOAuth2ConnectorBitbucketConfig();

            
            
            

            if (data.hasOwnProperty('clientID')) {
                obj['clientID'] = ApiClient.convertToType(data['clientID'], 'String');
            }
            if (data.hasOwnProperty('clientSecret')) {
                obj['clientSecret'] = ApiClient.convertToType(data['clientSecret'], 'String');
            }
            if (data.hasOwnProperty('redirectURI')) {
                obj['redirectURI'] = ApiClient.convertToType(data['redirectURI'], 'String');
            }
            if (data.hasOwnProperty('teams')) {
                obj['teams'] = ApiClient.convertToType(data['teams'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} clientID
    */
    clientID = undefined;
    /**
    * @member {String} clientSecret
    */
    clientSecret = undefined;
    /**
    * @member {String} redirectURI
    */
    redirectURI = undefined;
    /**
    * @member {Array.<String>} teams
    */
    teams = undefined;








}


