/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AuthOAuth2ConnectorSAMLConfig model module.
* @module model/AuthOAuth2ConnectorSAMLConfig
* @version 2.0
*/
export default class AuthOAuth2ConnectorSAMLConfig {
    /**
    * Constructs a new <code>AuthOAuth2ConnectorSAMLConfig</code>.
    * @alias module:model/AuthOAuth2ConnectorSAMLConfig
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AuthOAuth2ConnectorSAMLConfig</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthOAuth2ConnectorSAMLConfig} obj Optional instance to populate.
    * @return {module:model/AuthOAuth2ConnectorSAMLConfig} The populated <code>AuthOAuth2ConnectorSAMLConfig</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthOAuth2ConnectorSAMLConfig();

            
            
            

            if (data.hasOwnProperty('ssoURL')) {
                obj['ssoURL'] = ApiClient.convertToType(data['ssoURL'], 'String');
            }
            if (data.hasOwnProperty('ca')) {
                obj['ca'] = ApiClient.convertToType(data['ca'], 'String');
            }
            if (data.hasOwnProperty('redirectURI')) {
                obj['redirectURI'] = ApiClient.convertToType(data['redirectURI'], 'String');
            }
            if (data.hasOwnProperty('usernameAttr')) {
                obj['usernameAttr'] = ApiClient.convertToType(data['usernameAttr'], 'String');
            }
            if (data.hasOwnProperty('emailAttr')) {
                obj['emailAttr'] = ApiClient.convertToType(data['emailAttr'], 'String');
            }
            if (data.hasOwnProperty('groupsAttr')) {
                obj['groupsAttr'] = ApiClient.convertToType(data['groupsAttr'], 'String');
            }
            if (data.hasOwnProperty('caData')) {
                obj['caData'] = ApiClient.convertToType(data['caData'], 'String');
            }
            if (data.hasOwnProperty('insecureSkipSignatureValidation')) {
                obj['insecureSkipSignatureValidation'] = ApiClient.convertToType(data['insecureSkipSignatureValidation'], 'Boolean');
            }
            if (data.hasOwnProperty('entityIssuer')) {
                obj['entityIssuer'] = ApiClient.convertToType(data['entityIssuer'], 'String');
            }
            if (data.hasOwnProperty('ssoIssuer')) {
                obj['ssoIssuer'] = ApiClient.convertToType(data['ssoIssuer'], 'String');
            }
            if (data.hasOwnProperty('groupsDelim')) {
                obj['groupsDelim'] = ApiClient.convertToType(data['groupsDelim'], 'String');
            }
            if (data.hasOwnProperty('nameIDPolicyFormat')) {
                obj['nameIDPolicyFormat'] = ApiClient.convertToType(data['nameIDPolicyFormat'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} ssoURL
    */
    ssoURL = undefined;
    /**
    * @member {String} ca
    */
    ca = undefined;
    /**
    * @member {String} redirectURI
    */
    redirectURI = undefined;
    /**
    * @member {String} usernameAttr
    */
    usernameAttr = undefined;
    /**
    * @member {String} emailAttr
    */
    emailAttr = undefined;
    /**
    * @member {String} groupsAttr
    */
    groupsAttr = undefined;
    /**
    * @member {String} caData
    */
    caData = undefined;
    /**
    * @member {Boolean} insecureSkipSignatureValidation
    */
    insecureSkipSignatureValidation = undefined;
    /**
    * @member {String} entityIssuer
    */
    entityIssuer = undefined;
    /**
    * @member {String} ssoIssuer
    */
    ssoIssuer = undefined;
    /**
    * @member {String} groupsDelim
    */
    groupsDelim = undefined;
    /**
    * @member {String} nameIDPolicyFormat
    */
    nameIDPolicyFormat = undefined;








}


