/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import AuthOAuth2ConnectorConfig from './AuthOAuth2ConnectorConfig';





/**
* The AuthOAuth2ConnectorCollection model module.
* @module model/AuthOAuth2ConnectorCollection
* @version 2.0
*/
export default class AuthOAuth2ConnectorCollection {
    /**
    * Constructs a new <code>AuthOAuth2ConnectorCollection</code>.
    * @alias module:model/AuthOAuth2ConnectorCollection
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AuthOAuth2ConnectorCollection</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthOAuth2ConnectorCollection} obj Optional instance to populate.
    * @return {module:model/AuthOAuth2ConnectorCollection} The populated <code>AuthOAuth2ConnectorCollection</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthOAuth2ConnectorCollection();

            
            
            

            if (data.hasOwnProperty('connectors')) {
                obj['connectors'] = ApiClient.convertToType(data['connectors'], [AuthOAuth2ConnectorConfig]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/AuthOAuth2ConnectorConfig>} connectors
    */
    connectors = undefined;








}


