/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthOAuth2ConnectorGithubConfigOrg model module.
 * @module model/AuthOAuth2ConnectorGithubConfigOrg
 * @version 2.0
 */
class AuthOAuth2ConnectorGithubConfigOrg {
    /**
     * Constructs a new <code>AuthOAuth2ConnectorGithubConfigOrg</code>.
     * @alias module:model/AuthOAuth2ConnectorGithubConfigOrg
     */
    constructor() { 
        
        AuthOAuth2ConnectorGithubConfigOrg.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthOAuth2ConnectorGithubConfigOrg</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthOAuth2ConnectorGithubConfigOrg} obj Optional instance to populate.
     * @return {module:model/AuthOAuth2ConnectorGithubConfigOrg} The populated <code>AuthOAuth2ConnectorGithubConfigOrg</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthOAuth2ConnectorGithubConfigOrg();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('teams')) {
                obj['teams'] = ApiClient.convertToType(data['teams'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
AuthOAuth2ConnectorGithubConfigOrg.prototype['name'] = undefined;

/**
 * @member {Array.<String>} teams
 */
AuthOAuth2ConnectorGithubConfigOrg.prototype['teams'] = undefined;






export default AuthOAuth2ConnectorGithubConfigOrg;

