/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AuthOAuth2MappingRule model module.
* @module model/AuthOAuth2MappingRule
* @version 2.0
*/
export default class AuthOAuth2MappingRule {
    /**
    * Constructs a new <code>AuthOAuth2MappingRule</code>.
    * @alias module:model/AuthOAuth2MappingRule
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AuthOAuth2MappingRule</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthOAuth2MappingRule} obj Optional instance to populate.
    * @return {module:model/AuthOAuth2MappingRule} The populated <code>AuthOAuth2MappingRule</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthOAuth2MappingRule();

            
            
            

            if (data.hasOwnProperty('LeftAttribute')) {
                obj['LeftAttribute'] = ApiClient.convertToType(data['LeftAttribute'], 'String');
            }
            if (data.hasOwnProperty('RuleString')) {
                obj['RuleString'] = ApiClient.convertToType(data['RuleString'], 'String');
            }
            if (data.hasOwnProperty('RightAttribute')) {
                obj['RightAttribute'] = ApiClient.convertToType(data['RightAttribute'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} LeftAttribute
    */
    LeftAttribute = undefined;
    /**
    * @member {String} RuleString
    */
    RuleString = undefined;
    /**
    * @member {String} RightAttribute
    */
    RightAttribute = undefined;








}


