/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AuthOAuth2ClientConfig model module.
* @module model/AuthOAuth2ClientConfig
* @version 2.0
*/
export default class AuthOAuth2ClientConfig {
    /**
    * Constructs a new <code>AuthOAuth2ClientConfig</code>.
    * @alias module:model/AuthOAuth2ClientConfig
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AuthOAuth2ClientConfig</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthOAuth2ClientConfig} obj Optional instance to populate.
    * @return {module:model/AuthOAuth2ClientConfig} The populated <code>AuthOAuth2ClientConfig</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthOAuth2ClientConfig();

            
            
            

            if (data.hasOwnProperty('ClientID')) {
                obj['ClientID'] = ApiClient.convertToType(data['ClientID'], 'String');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('Secret')) {
                obj['Secret'] = ApiClient.convertToType(data['Secret'], 'String');
            }
            if (data.hasOwnProperty('RedirectURIs')) {
                obj['RedirectURIs'] = ApiClient.convertToType(data['RedirectURIs'], ['String']);
            }
            if (data.hasOwnProperty('GrantTypes')) {
                obj['GrantTypes'] = ApiClient.convertToType(data['GrantTypes'], ['String']);
            }
            if (data.hasOwnProperty('ResponseTypes')) {
                obj['ResponseTypes'] = ApiClient.convertToType(data['ResponseTypes'], ['String']);
            }
            if (data.hasOwnProperty('Scope')) {
                obj['Scope'] = ApiClient.convertToType(data['Scope'], 'String');
            }
            if (data.hasOwnProperty('Audience')) {
                obj['Audience'] = ApiClient.convertToType(data['Audience'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} ClientID
    */
    ClientID = undefined;
    /**
    * @member {String} Name
    */
    Name = undefined;
    /**
    * @member {String} Secret
    */
    Secret = undefined;
    /**
    * @member {Array.<String>} RedirectURIs
    */
    RedirectURIs = undefined;
    /**
    * @member {Array.<String>} GrantTypes
    */
    GrantTypes = undefined;
    /**
    * @member {Array.<String>} ResponseTypes
    */
    ResponseTypes = undefined;
    /**
    * @member {String} Scope
    */
    Scope = undefined;
    /**
    * @member {Array.<String>} Audience
    */
    Audience = undefined;








}


