/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthOAuth2ClientConfig model module.
 * @module model/AuthOAuth2ClientConfig
 * @version 2.0
 */
class AuthOAuth2ClientConfig {
    /**
     * Constructs a new <code>AuthOAuth2ClientConfig</code>.
     * @alias module:model/AuthOAuth2ClientConfig
     */
    constructor() { 
        
        AuthOAuth2ClientConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthOAuth2ClientConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthOAuth2ClientConfig} obj Optional instance to populate.
     * @return {module:model/AuthOAuth2ClientConfig} The populated <code>AuthOAuth2ClientConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthOAuth2ClientConfig();

            if (data.hasOwnProperty('audience')) {
                obj['audience'] = ApiClient.convertToType(data['audience'], ['String']);
            }
            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('client_name')) {
                obj['client_name'] = ApiClient.convertToType(data['client_name'], 'String');
            }
            if (data.hasOwnProperty('client_secret')) {
                obj['client_secret'] = ApiClient.convertToType(data['client_secret'], 'String');
            }
            if (data.hasOwnProperty('grant_types')) {
                obj['grant_types'] = ApiClient.convertToType(data['grant_types'], ['String']);
            }
            if (data.hasOwnProperty('redirect_uris')) {
                obj['redirect_uris'] = ApiClient.convertToType(data['redirect_uris'], ['String']);
            }
            if (data.hasOwnProperty('response_types')) {
                obj['response_types'] = ApiClient.convertToType(data['response_types'], ['String']);
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} audience
 */
AuthOAuth2ClientConfig.prototype['audience'] = undefined;

/**
 * @member {String} client_id
 */
AuthOAuth2ClientConfig.prototype['client_id'] = undefined;

/**
 * @member {String} client_name
 */
AuthOAuth2ClientConfig.prototype['client_name'] = undefined;

/**
 * @member {String} client_secret
 */
AuthOAuth2ClientConfig.prototype['client_secret'] = undefined;

/**
 * @member {Array.<String>} grant_types
 */
AuthOAuth2ClientConfig.prototype['grant_types'] = undefined;

/**
 * @member {Array.<String>} redirect_uris
 */
AuthOAuth2ClientConfig.prototype['redirect_uris'] = undefined;

/**
 * @member {Array.<String>} response_types
 */
AuthOAuth2ClientConfig.prototype['response_types'] = undefined;

/**
 * @member {String} scope
 */
AuthOAuth2ClientConfig.prototype['scope'] = undefined;






export default AuthOAuth2ClientConfig;

