/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthOAuth2ConnectorMicrosoftConfig model module.
 * @module model/AuthOAuth2ConnectorMicrosoftConfig
 * @version 2.0
 */
class AuthOAuth2ConnectorMicrosoftConfig {
    /**
     * Constructs a new <code>AuthOAuth2ConnectorMicrosoftConfig</code>.
     * @alias module:model/AuthOAuth2ConnectorMicrosoftConfig
     */
    constructor() { 
        
        AuthOAuth2ConnectorMicrosoftConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthOAuth2ConnectorMicrosoftConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthOAuth2ConnectorMicrosoftConfig} obj Optional instance to populate.
     * @return {module:model/AuthOAuth2ConnectorMicrosoftConfig} The populated <code>AuthOAuth2ConnectorMicrosoftConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthOAuth2ConnectorMicrosoftConfig();

            if (data.hasOwnProperty('clientID')) {
                obj['clientID'] = ApiClient.convertToType(data['clientID'], 'String');
            }
            if (data.hasOwnProperty('clientSecret')) {
                obj['clientSecret'] = ApiClient.convertToType(data['clientSecret'], 'String');
            }
            if (data.hasOwnProperty('groupNameFormat')) {
                obj['groupNameFormat'] = ApiClient.convertToType(data['groupNameFormat'], 'String');
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], ['String']);
            }
            if (data.hasOwnProperty('onlySecurityGroups')) {
                obj['onlySecurityGroups'] = ApiClient.convertToType(data['onlySecurityGroups'], 'Boolean');
            }
            if (data.hasOwnProperty('redirectURI')) {
                obj['redirectURI'] = ApiClient.convertToType(data['redirectURI'], 'String');
            }
            if (data.hasOwnProperty('tenant')) {
                obj['tenant'] = ApiClient.convertToType(data['tenant'], 'String');
            }
            if (data.hasOwnProperty('useGroupsAsWhitelist')) {
                obj['useGroupsAsWhitelist'] = ApiClient.convertToType(data['useGroupsAsWhitelist'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} clientID
 */
AuthOAuth2ConnectorMicrosoftConfig.prototype['clientID'] = undefined;

/**
 * @member {String} clientSecret
 */
AuthOAuth2ConnectorMicrosoftConfig.prototype['clientSecret'] = undefined;

/**
 * @member {String} groupNameFormat
 */
AuthOAuth2ConnectorMicrosoftConfig.prototype['groupNameFormat'] = undefined;

/**
 * @member {Array.<String>} groups
 */
AuthOAuth2ConnectorMicrosoftConfig.prototype['groups'] = undefined;

/**
 * @member {Boolean} onlySecurityGroups
 */
AuthOAuth2ConnectorMicrosoftConfig.prototype['onlySecurityGroups'] = undefined;

/**
 * @member {String} redirectURI
 */
AuthOAuth2ConnectorMicrosoftConfig.prototype['redirectURI'] = undefined;

/**
 * @member {String} tenant
 */
AuthOAuth2ConnectorMicrosoftConfig.prototype['tenant'] = undefined;

/**
 * @member {Boolean} useGroupsAsWhitelist
 */
AuthOAuth2ConnectorMicrosoftConfig.prototype['useGroupsAsWhitelist'] = undefined;






export default AuthOAuth2ConnectorMicrosoftConfig;

