/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuthLdapMapping from './AuthLdapMapping';
import AuthLdapSearchFilter from './AuthLdapSearchFilter';

/**
 * The AuthLdapMemberOfMapping model module.
 * @module model/AuthLdapMemberOfMapping
 * @version 2.0
 */
class AuthLdapMemberOfMapping {
    /**
     * Constructs a new <code>AuthLdapMemberOfMapping</code>.
     * @alias module:model/AuthLdapMemberOfMapping
     */
    constructor() { 
        
        AuthLdapMemberOfMapping.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthLdapMemberOfMapping</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthLdapMemberOfMapping} obj Optional instance to populate.
     * @return {module:model/AuthLdapMemberOfMapping} The populated <code>AuthLdapMemberOfMapping</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthLdapMemberOfMapping();

            if (data.hasOwnProperty('GroupFilter')) {
                obj['GroupFilter'] = AuthLdapSearchFilter.constructFromObject(data['GroupFilter']);
            }
            if (data.hasOwnProperty('Mapping')) {
                obj['Mapping'] = AuthLdapMapping.constructFromObject(data['Mapping']);
            }
            if (data.hasOwnProperty('PydioMemberOfAttribute')) {
                obj['PydioMemberOfAttribute'] = ApiClient.convertToType(data['PydioMemberOfAttribute'], 'String');
            }
            if (data.hasOwnProperty('PydioMemberOfValueFormat')) {
                obj['PydioMemberOfValueFormat'] = ApiClient.convertToType(data['PydioMemberOfValueFormat'], 'String');
            }
            if (data.hasOwnProperty('RealMemberOf')) {
                obj['RealMemberOf'] = ApiClient.convertToType(data['RealMemberOf'], 'Boolean');
            }
            if (data.hasOwnProperty('RealMemberOfAttribute')) {
                obj['RealMemberOfAttribute'] = ApiClient.convertToType(data['RealMemberOfAttribute'], 'String');
            }
            if (data.hasOwnProperty('RealMemberOfValueFormat')) {
                obj['RealMemberOfValueFormat'] = ApiClient.convertToType(data['RealMemberOfValueFormat'], 'String');
            }
            if (data.hasOwnProperty('SupportNestedGroup')) {
                obj['SupportNestedGroup'] = ApiClient.convertToType(data['SupportNestedGroup'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AuthLdapSearchFilter} GroupFilter
 */
AuthLdapMemberOfMapping.prototype['GroupFilter'] = undefined;

/**
 * @member {module:model/AuthLdapMapping} Mapping
 */
AuthLdapMemberOfMapping.prototype['Mapping'] = undefined;

/**
 * @member {String} PydioMemberOfAttribute
 */
AuthLdapMemberOfMapping.prototype['PydioMemberOfAttribute'] = undefined;

/**
 * @member {String} PydioMemberOfValueFormat
 */
AuthLdapMemberOfMapping.prototype['PydioMemberOfValueFormat'] = undefined;

/**
 * @member {Boolean} RealMemberOf
 */
AuthLdapMemberOfMapping.prototype['RealMemberOf'] = undefined;

/**
 * @member {String} RealMemberOfAttribute
 */
AuthLdapMemberOfMapping.prototype['RealMemberOfAttribute'] = undefined;

/**
 * @member {String} RealMemberOfValueFormat
 */
AuthLdapMemberOfMapping.prototype['RealMemberOfValueFormat'] = undefined;

/**
 * @member {Boolean} SupportNestedGroup
 */
AuthLdapMemberOfMapping.prototype['SupportNestedGroup'] = undefined;






export default AuthLdapMemberOfMapping;

