/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import AuthLdapServerConfig from './AuthLdapServerConfig';
import AuthOAuth2ConnectorBitbucketConfig from './AuthOAuth2ConnectorBitbucketConfig';
import AuthOAuth2ConnectorGithubConfig from './AuthOAuth2ConnectorGithubConfig';
import AuthOAuth2ConnectorGitlabConfig from './AuthOAuth2ConnectorGitlabConfig';
import AuthOAuth2ConnectorLinkedinConfig from './AuthOAuth2ConnectorLinkedinConfig';
import AuthOAuth2ConnectorMicrosoftConfig from './AuthOAuth2ConnectorMicrosoftConfig';
import AuthOAuth2ConnectorOAuthConfig from './AuthOAuth2ConnectorOAuthConfig';
import AuthOAuth2ConnectorOIDCConfig from './AuthOAuth2ConnectorOIDCConfig';
import AuthOAuth2ConnectorPydioConfig from './AuthOAuth2ConnectorPydioConfig';
import AuthOAuth2ConnectorSAMLConfig from './AuthOAuth2ConnectorSAMLConfig';
import AuthOAuth2MappingRule from './AuthOAuth2MappingRule';





/**
* The AuthOAuth2ConnectorConfig model module.
* @module model/AuthOAuth2ConnectorConfig
* @version 2.0
*/
export default class AuthOAuth2ConnectorConfig {
    /**
    * Constructs a new <code>AuthOAuth2ConnectorConfig</code>.
    * @alias module:model/AuthOAuth2ConnectorConfig
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AuthOAuth2ConnectorConfig</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthOAuth2ConnectorConfig} obj Optional instance to populate.
    * @return {module:model/AuthOAuth2ConnectorConfig} The populated <code>AuthOAuth2ConnectorConfig</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthOAuth2ConnectorConfig();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('mappingRules')) {
                obj['mappingRules'] = ApiClient.convertToType(data['mappingRules'], [AuthOAuth2MappingRule]);
            }
            if (data.hasOwnProperty('configpydio')) {
                obj['configpydio'] = AuthOAuth2ConnectorPydioConfig.constructFromObject(data['configpydio']);
            }
            if (data.hasOwnProperty('configoidc')) {
                obj['configoidc'] = AuthOAuth2ConnectorOIDCConfig.constructFromObject(data['configoidc']);
            }
            if (data.hasOwnProperty('configsaml')) {
                obj['configsaml'] = AuthOAuth2ConnectorSAMLConfig.constructFromObject(data['configsaml']);
            }
            if (data.hasOwnProperty('configbitbucket')) {
                obj['configbitbucket'] = AuthOAuth2ConnectorBitbucketConfig.constructFromObject(data['configbitbucket']);
            }
            if (data.hasOwnProperty('configgithub')) {
                obj['configgithub'] = AuthOAuth2ConnectorGithubConfig.constructFromObject(data['configgithub']);
            }
            if (data.hasOwnProperty('configgitlab')) {
                obj['configgitlab'] = AuthOAuth2ConnectorGitlabConfig.constructFromObject(data['configgitlab']);
            }
            if (data.hasOwnProperty('configlinkedin')) {
                obj['configlinkedin'] = AuthOAuth2ConnectorLinkedinConfig.constructFromObject(data['configlinkedin']);
            }
            if (data.hasOwnProperty('configmicrosoft')) {
                obj['configmicrosoft'] = AuthOAuth2ConnectorMicrosoftConfig.constructFromObject(data['configmicrosoft']);
            }
            if (data.hasOwnProperty('configldap')) {
                obj['configldap'] = AuthLdapServerConfig.constructFromObject(data['configldap']);
            }
            if (data.hasOwnProperty('configoauth')) {
                obj['configoauth'] = AuthOAuth2ConnectorOAuthConfig.constructFromObject(data['configoauth']);
            }
            if (data.hasOwnProperty('sites')) {
                obj['sites'] = ApiClient.convertToType(data['sites'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} type
    */
    type = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {Array.<module:model/AuthOAuth2MappingRule>} mappingRules
    */
    mappingRules = undefined;
    /**
    * @member {module:model/AuthOAuth2ConnectorPydioConfig} configpydio
    */
    configpydio = undefined;
    /**
    * @member {module:model/AuthOAuth2ConnectorOIDCConfig} configoidc
    */
    configoidc = undefined;
    /**
    * @member {module:model/AuthOAuth2ConnectorSAMLConfig} configsaml
    */
    configsaml = undefined;
    /**
    * @member {module:model/AuthOAuth2ConnectorBitbucketConfig} configbitbucket
    */
    configbitbucket = undefined;
    /**
    * @member {module:model/AuthOAuth2ConnectorGithubConfig} configgithub
    */
    configgithub = undefined;
    /**
    * @member {module:model/AuthOAuth2ConnectorGitlabConfig} configgitlab
    */
    configgitlab = undefined;
    /**
    * @member {module:model/AuthOAuth2ConnectorLinkedinConfig} configlinkedin
    */
    configlinkedin = undefined;
    /**
    * @member {module:model/AuthOAuth2ConnectorMicrosoftConfig} configmicrosoft
    */
    configmicrosoft = undefined;
    /**
    * @member {module:model/AuthLdapServerConfig} configldap
    */
    configldap = undefined;
    /**
    * @member {module:model/AuthOAuth2ConnectorOAuthConfig} configoauth
    */
    configoauth = undefined;
    /**
    * @member {Array.<String>} sites
    */
    sites = undefined;








}


