/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CertLicenseInfo model module.
 * @module model/CertLicenseInfo
 * @version 2.0
 */
class CertLicenseInfo {
    /**
     * Constructs a new <code>CertLicenseInfo</code>.
     * @alias module:model/CertLicenseInfo
     */
    constructor() { 
        
        CertLicenseInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertLicenseInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertLicenseInfo} obj Optional instance to populate.
     * @return {module:model/CertLicenseInfo} The populated <code>CertLicenseInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertLicenseInfo();

            if (data.hasOwnProperty('AccountName')) {
                obj['AccountName'] = ApiClient.convertToType(data['AccountName'], 'String');
            }
            if (data.hasOwnProperty('ExpireTime')) {
                obj['ExpireTime'] = ApiClient.convertToType(data['ExpireTime'], 'Number');
            }
            if (data.hasOwnProperty('Features')) {
                obj['Features'] = ApiClient.convertToType(data['Features'], {'String': 'String'});
            }
            if (data.hasOwnProperty('Id')) {
                obj['Id'] = ApiClient.convertToType(data['Id'], 'String');
            }
            if (data.hasOwnProperty('IssueTime')) {
                obj['IssueTime'] = ApiClient.convertToType(data['IssueTime'], 'Number');
            }
            if (data.hasOwnProperty('MaxPeers')) {
                obj['MaxPeers'] = ApiClient.convertToType(data['MaxPeers'], 'String');
            }
            if (data.hasOwnProperty('MaxUsers')) {
                obj['MaxUsers'] = ApiClient.convertToType(data['MaxUsers'], 'String');
            }
            if (data.hasOwnProperty('ServerDomain')) {
                obj['ServerDomain'] = ApiClient.convertToType(data['ServerDomain'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} AccountName
 */
CertLicenseInfo.prototype['AccountName'] = undefined;

/**
 * @member {Number} ExpireTime
 */
CertLicenseInfo.prototype['ExpireTime'] = undefined;

/**
 * @member {Object.<String, String>} Features
 */
CertLicenseInfo.prototype['Features'] = undefined;

/**
 * @member {String} Id
 */
CertLicenseInfo.prototype['Id'] = undefined;

/**
 * @member {Number} IssueTime
 */
CertLicenseInfo.prototype['IssueTime'] = undefined;

/**
 * @member {String} MaxPeers
 */
CertLicenseInfo.prototype['MaxPeers'] = undefined;

/**
 * @member {String} MaxUsers
 */
CertLicenseInfo.prototype['MaxUsers'] = undefined;

/**
 * @member {String} ServerDomain
 */
CertLicenseInfo.prototype['ServerDomain'] = undefined;






export default CertLicenseInfo;

