/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The CertPutLicenseInfoRequest model module.
* @module model/CertPutLicenseInfoRequest
* @version 2.0
*/
export default class CertPutLicenseInfoRequest {
    /**
    * Constructs a new <code>CertPutLicenseInfoRequest</code>.
    * @alias module:model/CertPutLicenseInfoRequest
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>CertPutLicenseInfoRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CertPutLicenseInfoRequest} obj Optional instance to populate.
    * @return {module:model/CertPutLicenseInfoRequest} The populated <code>CertPutLicenseInfoRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertPutLicenseInfoRequest();

            
            
            

            if (data.hasOwnProperty('LicenseString')) {
                obj['LicenseString'] = ApiClient.convertToType(data['LicenseString'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} LicenseString
    */
    LicenseString = undefined;








}


