/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CertPutLicenseInfoRequest model module.
 * @module model/CertPutLicenseInfoRequest
 * @version 2.0
 */
class CertPutLicenseInfoRequest {
    /**
     * Constructs a new <code>CertPutLicenseInfoRequest</code>.
     * @alias module:model/CertPutLicenseInfoRequest
     */
    constructor() { 
        
        CertPutLicenseInfoRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertPutLicenseInfoRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertPutLicenseInfoRequest} obj Optional instance to populate.
     * @return {module:model/CertPutLicenseInfoRequest} The populated <code>CertPutLicenseInfoRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertPutLicenseInfoRequest();

            if (data.hasOwnProperty('LicenseString')) {
                obj['LicenseString'] = ApiClient.convertToType(data['LicenseString'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} LicenseString
 */
CertPutLicenseInfoRequest.prototype['LicenseString'] = undefined;






export default CertPutLicenseInfoRequest;

