/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import JobsAction from './JobsAction';





/**
* The EntActionTemplate model module.
* @module model/EntActionTemplate
* @version 2.0
*/
export default class EntActionTemplate {
    /**
    * Constructs a new <code>EntActionTemplate</code>.
    * @alias module:model/EntActionTemplate
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EntActionTemplate</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EntActionTemplate} obj Optional instance to populate.
    * @return {module:model/EntActionTemplate} The populated <code>EntActionTemplate</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntActionTemplate();

            
            
            

            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('Action')) {
                obj['Action'] = JobsAction.constructFromObject(data['Action']);
            }
        }
        return obj;
    }

    /**
    * @member {String} Name
    */
    Name = undefined;
    /**
    * @member {module:model/JobsAction} Action
    */
    Action = undefined;








}


