/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServiceResourcePolicy from './ServiceResourcePolicy';

/**
 * The EntCreateNodeTemplateRequest model module.
 * @module model/EntCreateNodeTemplateRequest
 * @version 2.0
 */
class EntCreateNodeTemplateRequest {
    /**
     * Constructs a new <code>EntCreateNodeTemplateRequest</code>.
     * @alias module:model/EntCreateNodeTemplateRequest
     */
    constructor() { 
        
        EntCreateNodeTemplateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntCreateNodeTemplateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntCreateNodeTemplateRequest} obj Optional instance to populate.
     * @return {module:model/EntCreateNodeTemplateRequest} The populated <code>EntCreateNodeTemplateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntCreateNodeTemplateRequest();

            if (data.hasOwnProperty('Policies')) {
                obj['Policies'] = ApiClient.convertToType(data['Policies'], [ServiceResourcePolicy]);
            }
            if (data.hasOwnProperty('RefNodeUuid')) {
                obj['RefNodeUuid'] = ApiClient.convertToType(data['RefNodeUuid'], 'String');
            }
            if (data.hasOwnProperty('TplLabel')) {
                obj['TplLabel'] = ApiClient.convertToType(data['TplLabel'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ServiceResourcePolicy>} Policies
 */
EntCreateNodeTemplateRequest.prototype['Policies'] = undefined;

/**
 * @member {String} RefNodeUuid
 */
EntCreateNodeTemplateRequest.prototype['RefNodeUuid'] = undefined;

/**
 * @member {String} TplLabel
 */
EntCreateNodeTemplateRequest.prototype['TplLabel'] = undefined;






export default EntCreateNodeTemplateRequest;

