/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The EntDocTemplatePiece model module.
* @module model/EntDocTemplatePiece
* @version 2.0
*/
export default class EntDocTemplatePiece {
    /**
    * Constructs a new <code>EntDocTemplatePiece</code>.
    * @alias module:model/EntDocTemplatePiece
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EntDocTemplatePiece</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EntDocTemplatePiece} obj Optional instance to populate.
    * @return {module:model/EntDocTemplatePiece} The populated <code>EntDocTemplatePiece</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntDocTemplatePiece();

            
            
            

            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('Context')) {
                obj['Context'] = ApiClient.convertToType(data['Context'], 'String');
            }
            if (data.hasOwnProperty('Short')) {
                obj['Short'] = ApiClient.convertToType(data['Short'], 'String');
            }
            if (data.hasOwnProperty('Long')) {
                obj['Long'] = ApiClient.convertToType(data['Long'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} Name
    */
    Name = undefined;
    /**
    * @member {String} Context
    */
    Context = undefined;
    /**
    * @member {String} Short
    */
    Short = undefined;
    /**
    * @member {String} Long
    */
    Long = undefined;








}


