/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntDocTemplatePiece model module.
 * @module model/EntDocTemplatePiece
 * @version 2.0
 */
class EntDocTemplatePiece {
    /**
     * Constructs a new <code>EntDocTemplatePiece</code>.
     * @alias module:model/EntDocTemplatePiece
     */
    constructor() { 
        
        EntDocTemplatePiece.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntDocTemplatePiece</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntDocTemplatePiece} obj Optional instance to populate.
     * @return {module:model/EntDocTemplatePiece} The populated <code>EntDocTemplatePiece</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntDocTemplatePiece();

            if (data.hasOwnProperty('Context')) {
                obj['Context'] = ApiClient.convertToType(data['Context'], 'String');
            }
            if (data.hasOwnProperty('Long')) {
                obj['Long'] = ApiClient.convertToType(data['Long'], 'String');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('Short')) {
                obj['Short'] = ApiClient.convertToType(data['Short'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} Context
 */
EntDocTemplatePiece.prototype['Context'] = undefined;

/**
 * @member {String} Long
 */
EntDocTemplatePiece.prototype['Long'] = undefined;

/**
 * @member {String} Name
 */
EntDocTemplatePiece.prototype['Name'] = undefined;

/**
 * @member {String} Short
 */
EntDocTemplatePiece.prototype['Short'] = undefined;






export default EntDocTemplatePiece;

