/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuthLdapServerConfig from './AuthLdapServerConfig';

/**
 * The EntExternalDirectoryConfig model module.
 * @module model/EntExternalDirectoryConfig
 * @version 2.0
 */
class EntExternalDirectoryConfig {
    /**
     * Constructs a new <code>EntExternalDirectoryConfig</code>.
     * @alias module:model/EntExternalDirectoryConfig
     */
    constructor() { 
        
        EntExternalDirectoryConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntExternalDirectoryConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntExternalDirectoryConfig} obj Optional instance to populate.
     * @return {module:model/EntExternalDirectoryConfig} The populated <code>EntExternalDirectoryConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntExternalDirectoryConfig();

            if (data.hasOwnProperty('Config')) {
                obj['Config'] = AuthLdapServerConfig.constructFromObject(data['Config']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AuthLdapServerConfig} Config
 */
EntExternalDirectoryConfig.prototype['Config'] = undefined;






export default EntExternalDirectoryConfig;

