/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import AuthLdapServerConfig from './AuthLdapServerConfig';





/**
* The EntExternalDirectoryConfig model module.
* @module model/EntExternalDirectoryConfig
* @version 2.0
*/
export default class EntExternalDirectoryConfig {
    /**
    * Constructs a new <code>EntExternalDirectoryConfig</code>.
    * @alias module:model/EntExternalDirectoryConfig
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EntExternalDirectoryConfig</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EntExternalDirectoryConfig} obj Optional instance to populate.
    * @return {module:model/EntExternalDirectoryConfig} The populated <code>EntExternalDirectoryConfig</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntExternalDirectoryConfig();

            
            
            

            if (data.hasOwnProperty('ConfigId')) {
                obj['ConfigId'] = ApiClient.convertToType(data['ConfigId'], 'String');
            }
            if (data.hasOwnProperty('Config')) {
                obj['Config'] = AuthLdapServerConfig.constructFromObject(data['Config']);
            }
        }
        return obj;
    }

    /**
    * @member {String} ConfigId
    */
    ConfigId = undefined;
    /**
    * @member {module:model/AuthLdapServerConfig} Config
    */
    Config = undefined;








}


