/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntConnector from './EntConnector';

/**
 * The EntFrontLoginConnectorsResponse model module.
 * @module model/EntFrontLoginConnectorsResponse
 * @version 2.0
 */
class EntFrontLoginConnectorsResponse {
    /**
     * Constructs a new <code>EntFrontLoginConnectorsResponse</code>.
     * @alias module:model/EntFrontLoginConnectorsResponse
     */
    constructor() { 
        
        EntFrontLoginConnectorsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntFrontLoginConnectorsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntFrontLoginConnectorsResponse} obj Optional instance to populate.
     * @return {module:model/EntFrontLoginConnectorsResponse} The populated <code>EntFrontLoginConnectorsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntFrontLoginConnectorsResponse();

            if (data.hasOwnProperty('Connectors')) {
                obj['Connectors'] = ApiClient.convertToType(data['Connectors'], [EntConnector]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/EntConnector>} Connectors
 */
EntFrontLoginConnectorsResponse.prototype['Connectors'] = undefined;






export default EntFrontLoginConnectorsResponse;

