/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import EntConnector from './EntConnector';





/**
* The EntFrontLoginConnectorsResponse model module.
* @module model/EntFrontLoginConnectorsResponse
* @version 2.0
*/
export default class EntFrontLoginConnectorsResponse {
    /**
    * Constructs a new <code>EntFrontLoginConnectorsResponse</code>.
    * @alias module:model/EntFrontLoginConnectorsResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EntFrontLoginConnectorsResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EntFrontLoginConnectorsResponse} obj Optional instance to populate.
    * @return {module:model/EntFrontLoginConnectorsResponse} The populated <code>EntFrontLoginConnectorsResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntFrontLoginConnectorsResponse();

            
            
            

            if (data.hasOwnProperty('Connectors')) {
                obj['Connectors'] = ApiClient.convertToType(data['Connectors'], [EntConnector]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/EntConnector>} Connectors
    */
    Connectors = undefined;








}


