/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntJobVersion from './EntJobVersion';

/**
 * The EntListJobVersionsResponse model module.
 * @module model/EntListJobVersionsResponse
 * @version 2.0
 */
class EntListJobVersionsResponse {
    /**
     * Constructs a new <code>EntListJobVersionsResponse</code>.
     * @alias module:model/EntListJobVersionsResponse
     */
    constructor() { 
        
        EntListJobVersionsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntListJobVersionsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntListJobVersionsResponse} obj Optional instance to populate.
     * @return {module:model/EntListJobVersionsResponse} The populated <code>EntListJobVersionsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntListJobVersionsResponse();

            if (data.hasOwnProperty('Versions')) {
                obj['Versions'] = ApiClient.convertToType(data['Versions'], [EntJobVersion]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/EntJobVersion>} Versions
 */
EntListJobVersionsResponse.prototype['Versions'] = undefined;






export default EntListJobVersionsResponse;

