/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntActionTemplate from './EntActionTemplate';

/**
 * The EntListActionTemplatesResponse model module.
 * @module model/EntListActionTemplatesResponse
 * @version 2.0
 */
class EntListActionTemplatesResponse {
    /**
     * Constructs a new <code>EntListActionTemplatesResponse</code>.
     * @alias module:model/EntListActionTemplatesResponse
     */
    constructor() { 
        
        EntListActionTemplatesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntListActionTemplatesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntListActionTemplatesResponse} obj Optional instance to populate.
     * @return {module:model/EntListActionTemplatesResponse} The populated <code>EntListActionTemplatesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntListActionTemplatesResponse();

            if (data.hasOwnProperty('Templates')) {
                obj['Templates'] = ApiClient.convertToType(data['Templates'], [EntActionTemplate]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/EntActionTemplate>} Templates
 */
EntListActionTemplatesResponse.prototype['Templates'] = undefined;






export default EntListActionTemplatesResponse;

