/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntListAccessTokensRequest model module.
 * @module model/EntListAccessTokensRequest
 * @version 2.0
 */
class EntListAccessTokensRequest {
    /**
     * Constructs a new <code>EntListAccessTokensRequest</code>.
     * @alias module:model/EntListAccessTokensRequest
     */
    constructor() { 
        
        EntListAccessTokensRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntListAccessTokensRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntListAccessTokensRequest} obj Optional instance to populate.
     * @return {module:model/EntListAccessTokensRequest} The populated <code>EntListAccessTokensRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntListAccessTokensRequest();

            if (data.hasOwnProperty('ByUser')) {
                obj['ByUser'] = ApiClient.convertToType(data['ByUser'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} ByUser
 */
EntListAccessTokensRequest.prototype['ByUser'] = undefined;






export default EntListAccessTokensRequest;

