/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobsJob from './JobsJob';

/**
 * The EntListJobTemplatesResponse model module.
 * @module model/EntListJobTemplatesResponse
 * @version 2.0
 */
class EntListJobTemplatesResponse {
    /**
     * Constructs a new <code>EntListJobTemplatesResponse</code>.
     * @alias module:model/EntListJobTemplatesResponse
     */
    constructor() { 
        
        EntListJobTemplatesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntListJobTemplatesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntListJobTemplatesResponse} obj Optional instance to populate.
     * @return {module:model/EntListJobTemplatesResponse} The populated <code>EntListJobTemplatesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntListJobTemplatesResponse();

            if (data.hasOwnProperty('Jobs')) {
                obj['Jobs'] = ApiClient.convertToType(data['Jobs'], [JobsJob]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/JobsJob>} Jobs
 */
EntListJobTemplatesResponse.prototype['Jobs'] = undefined;






export default EntListJobTemplatesResponse;

