/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import InstallProxyConfig from './InstallProxyConfig';





/**
* The EntListSitesResponse model module.
* @module model/EntListSitesResponse
* @version 2.0
*/
export default class EntListSitesResponse {
    /**
    * Constructs a new <code>EntListSitesResponse</code>.
    * @alias module:model/EntListSitesResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EntListSitesResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EntListSitesResponse} obj Optional instance to populate.
    * @return {module:model/EntListSitesResponse} The populated <code>EntListSitesResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntListSitesResponse();

            
            
            

            if (data.hasOwnProperty('Sites')) {
                obj['Sites'] = ApiClient.convertToType(data['Sites'], [InstallProxyConfig]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/InstallProxyConfig>} Sites
    */
    Sites = undefined;








}


