/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The EntListActionTemplatesRequest model module.
* @module model/EntListActionTemplatesRequest
* @version 2.0
*/
export default class EntListActionTemplatesRequest {
    /**
    * Constructs a new <code>EntListActionTemplatesRequest</code>.
    * @alias module:model/EntListActionTemplatesRequest
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EntListActionTemplatesRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EntListActionTemplatesRequest} obj Optional instance to populate.
    * @return {module:model/EntListActionTemplatesRequest} The populated <code>EntListActionTemplatesRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntListActionTemplatesRequest();

            
            
            

        }
        return obj;
    }









}


