/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The EntListSelectorTemplatesRequest model module.
* @module model/EntListSelectorTemplatesRequest
* @version 2.0
*/
export default class EntListSelectorTemplatesRequest {
    /**
    * Constructs a new <code>EntListSelectorTemplatesRequest</code>.
    * @alias module:model/EntListSelectorTemplatesRequest
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EntListSelectorTemplatesRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EntListSelectorTemplatesRequest} obj Optional instance to populate.
    * @return {module:model/EntListSelectorTemplatesRequest} The populated <code>EntListSelectorTemplatesRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntListSelectorTemplatesRequest();

            
            
            

            if (data.hasOwnProperty('Filter')) {
                obj['Filter'] = ApiClient.convertToType(data['Filter'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} Filter
    */
    Filter = undefined;








}


