/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuthOAuth2ClientConfig from './AuthOAuth2ClientConfig';

/**
 * The EntOAuth2ClientCollection model module.
 * @module model/EntOAuth2ClientCollection
 * @version 2.0
 */
class EntOAuth2ClientCollection {
    /**
     * Constructs a new <code>EntOAuth2ClientCollection</code>.
     * @alias module:model/EntOAuth2ClientCollection
     */
    constructor() { 
        
        EntOAuth2ClientCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntOAuth2ClientCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntOAuth2ClientCollection} obj Optional instance to populate.
     * @return {module:model/EntOAuth2ClientCollection} The populated <code>EntOAuth2ClientCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntOAuth2ClientCollection();

            if (data.hasOwnProperty('staticClients')) {
                obj['staticClients'] = ApiClient.convertToType(data['staticClients'], [AuthOAuth2ClientConfig]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/AuthOAuth2ClientConfig>} staticClients
 */
EntOAuth2ClientCollection.prototype['staticClients'] = undefined;






export default EntOAuth2ClientCollection;

