/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntOAuth2ClientResponse model module.
 * @module model/EntOAuth2ClientResponse
 * @version 2.0
 */
class EntOAuth2ClientResponse {
    /**
     * Constructs a new <code>EntOAuth2ClientResponse</code>.
     * @alias module:model/EntOAuth2ClientResponse
     */
    constructor() { 
        
        EntOAuth2ClientResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntOAuth2ClientResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntOAuth2ClientResponse} obj Optional instance to populate.
     * @return {module:model/EntOAuth2ClientResponse} The populated <code>EntOAuth2ClientResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntOAuth2ClientResponse();

            if (data.hasOwnProperty('Success')) {
                obj['Success'] = ApiClient.convertToType(data['Success'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} Success
 */
EntOAuth2ClientResponse.prototype['Success'] = undefined;






export default EntOAuth2ClientResponse;

