/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntPersonalAccessTokenResponse model module.
 * @module model/EntPersonalAccessTokenResponse
 * @version 2.0
 */
class EntPersonalAccessTokenResponse {
    /**
     * Constructs a new <code>EntPersonalAccessTokenResponse</code>.
     * @alias module:model/EntPersonalAccessTokenResponse
     */
    constructor() { 
        
        EntPersonalAccessTokenResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntPersonalAccessTokenResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntPersonalAccessTokenResponse} obj Optional instance to populate.
     * @return {module:model/EntPersonalAccessTokenResponse} The populated <code>EntPersonalAccessTokenResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntPersonalAccessTokenResponse();

            if (data.hasOwnProperty('AccessToken')) {
                obj['AccessToken'] = ApiClient.convertToType(data['AccessToken'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} AccessToken
 */
EntPersonalAccessTokenResponse.prototype['AccessToken'] = undefined;






export default EntPersonalAccessTokenResponse;

