/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The EntPersonalAccessTokenResponse model module.
* @module model/EntPersonalAccessTokenResponse
* @version 2.0
*/
export default class EntPersonalAccessTokenResponse {
    /**
    * Constructs a new <code>EntPersonalAccessTokenResponse</code>.
    * @alias module:model/EntPersonalAccessTokenResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EntPersonalAccessTokenResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EntPersonalAccessTokenResponse} obj Optional instance to populate.
    * @return {module:model/EntPersonalAccessTokenResponse} The populated <code>EntPersonalAccessTokenResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntPersonalAccessTokenResponse();

            
            
            

            if (data.hasOwnProperty('AccessToken')) {
                obj['AccessToken'] = ApiClient.convertToType(data['AccessToken'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} AccessToken
    */
    AccessToken = undefined;








}


