/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import EntActionTemplate from './EntActionTemplate';





/**
* The EntPutActionTemplateResponse model module.
* @module model/EntPutActionTemplateResponse
* @version 2.0
*/
export default class EntPutActionTemplateResponse {
    /**
    * Constructs a new <code>EntPutActionTemplateResponse</code>.
    * @alias module:model/EntPutActionTemplateResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EntPutActionTemplateResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EntPutActionTemplateResponse} obj Optional instance to populate.
    * @return {module:model/EntPutActionTemplateResponse} The populated <code>EntPutActionTemplateResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntPutActionTemplateResponse();

            
            
            

            if (data.hasOwnProperty('Template')) {
                obj['Template'] = EntActionTemplate.constructFromObject(data['Template']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/EntActionTemplate} Template
    */
    Template = undefined;








}


