/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobsActionMessage from './JobsActionMessage';

/**
 * The EntPlaygroundRequest model module.
 * @module model/EntPlaygroundRequest
 * @version 2.0
 */
class EntPlaygroundRequest {
    /**
     * Constructs a new <code>EntPlaygroundRequest</code>.
     * @alias module:model/EntPlaygroundRequest
     */
    constructor() { 
        
        EntPlaygroundRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntPlaygroundRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntPlaygroundRequest} obj Optional instance to populate.
     * @return {module:model/EntPlaygroundRequest} The populated <code>EntPlaygroundRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntPlaygroundRequest();

            if (data.hasOwnProperty('Code')) {
                obj['Code'] = ApiClient.convertToType(data['Code'], 'String');
            }
            if (data.hasOwnProperty('Input')) {
                obj['Input'] = JobsActionMessage.constructFromObject(data['Input']);
            }
            if (data.hasOwnProperty('LastOutputJsonBody')) {
                obj['LastOutputJsonBody'] = ApiClient.convertToType(data['LastOutputJsonBody'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} Code
 */
EntPlaygroundRequest.prototype['Code'] = undefined;

/**
 * @member {module:model/JobsActionMessage} Input
 */
EntPlaygroundRequest.prototype['Input'] = undefined;

/**
 * @member {String} LastOutputJsonBody
 */
EntPlaygroundRequest.prototype['LastOutputJsonBody'] = undefined;






export default EntPlaygroundRequest;

