/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntPersonalAccessTokenRequest model module.
 * @module model/EntPersonalAccessTokenRequest
 * @version 2.0
 */
class EntPersonalAccessTokenRequest {
    /**
     * Constructs a new <code>EntPersonalAccessTokenRequest</code>.
     * @alias module:model/EntPersonalAccessTokenRequest
     */
    constructor() { 
        
        EntPersonalAccessTokenRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntPersonalAccessTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntPersonalAccessTokenRequest} obj Optional instance to populate.
     * @return {module:model/EntPersonalAccessTokenRequest} The populated <code>EntPersonalAccessTokenRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntPersonalAccessTokenRequest();

            if (data.hasOwnProperty('AutoRefresh')) {
                obj['AutoRefresh'] = ApiClient.convertToType(data['AutoRefresh'], 'Number');
            }
            if (data.hasOwnProperty('ExpiresAt')) {
                obj['ExpiresAt'] = ApiClient.convertToType(data['ExpiresAt'], 'String');
            }
            if (data.hasOwnProperty('Label')) {
                obj['Label'] = ApiClient.convertToType(data['Label'], 'String');
            }
            if (data.hasOwnProperty('Scopes')) {
                obj['Scopes'] = ApiClient.convertToType(data['Scopes'], ['String']);
            }
            if (data.hasOwnProperty('UserLogin')) {
                obj['UserLogin'] = ApiClient.convertToType(data['UserLogin'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} AutoRefresh
 */
EntPersonalAccessTokenRequest.prototype['AutoRefresh'] = undefined;

/**
 * @member {String} ExpiresAt
 */
EntPersonalAccessTokenRequest.prototype['ExpiresAt'] = undefined;

/**
 * @member {String} Label
 */
EntPersonalAccessTokenRequest.prototype['Label'] = undefined;

/**
 * @member {Array.<String>} Scopes
 */
EntPersonalAccessTokenRequest.prototype['Scopes'] = undefined;

/**
 * @member {String} UserLogin
 */
EntPersonalAccessTokenRequest.prototype['UserLogin'] = undefined;






export default EntPersonalAccessTokenRequest;

