/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import JobsActionMessage from './JobsActionMessage';





/**
* The EntPlaygroundRequest model module.
* @module model/EntPlaygroundRequest
* @version 2.0
*/
export default class EntPlaygroundRequest {
    /**
    * Constructs a new <code>EntPlaygroundRequest</code>.
    * @alias module:model/EntPlaygroundRequest
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EntPlaygroundRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EntPlaygroundRequest} obj Optional instance to populate.
    * @return {module:model/EntPlaygroundRequest} The populated <code>EntPlaygroundRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntPlaygroundRequest();

            
            
            

            if (data.hasOwnProperty('Input')) {
                obj['Input'] = JobsActionMessage.constructFromObject(data['Input']);
            }
            if (data.hasOwnProperty('LastOutputJsonBody')) {
                obj['LastOutputJsonBody'] = ApiClient.convertToType(data['LastOutputJsonBody'], 'String');
            }
            if (data.hasOwnProperty('Code')) {
                obj['Code'] = ApiClient.convertToType(data['Code'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/JobsActionMessage} Input
    */
    Input = undefined;
    /**
    * @member {String} LastOutputJsonBody
    */
    LastOutputJsonBody = undefined;
    /**
    * @member {String} Code
    */
    Code = undefined;








}


