/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobsActionOutputFilter from './JobsActionOutputFilter';
import JobsContextMetaFilter from './JobsContextMetaFilter';
import JobsDataSourceSelector from './JobsDataSourceSelector';
import JobsIdmSelector from './JobsIdmSelector';
import JobsNodesSelector from './JobsNodesSelector';
import JobsTriggerFilter from './JobsTriggerFilter';

/**
 * The EntSelectorTemplate model module.
 * @module model/EntSelectorTemplate
 * @version 2.0
 */
class EntSelectorTemplate {
    /**
     * Constructs a new <code>EntSelectorTemplate</code>.
     * @alias module:model/EntSelectorTemplate
     */
    constructor() { 
        
        EntSelectorTemplate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntSelectorTemplate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntSelectorTemplate} obj Optional instance to populate.
     * @return {module:model/EntSelectorTemplate} The populated <code>EntSelectorTemplate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntSelectorTemplate();

            if (data.hasOwnProperty('ActionOutputFilter')) {
                obj['ActionOutputFilter'] = JobsActionOutputFilter.constructFromObject(data['ActionOutputFilter']);
            }
            if (data.hasOwnProperty('AsFilter')) {
                obj['AsFilter'] = ApiClient.convertToType(data['AsFilter'], 'Boolean');
            }
            if (data.hasOwnProperty('ContextMetaFilter')) {
                obj['ContextMetaFilter'] = JobsContextMetaFilter.constructFromObject(data['ContextMetaFilter']);
            }
            if (data.hasOwnProperty('DataSourceSelector')) {
                obj['DataSourceSelector'] = JobsDataSourceSelector.constructFromObject(data['DataSourceSelector']);
            }
            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
            if (data.hasOwnProperty('IdmSelector')) {
                obj['IdmSelector'] = JobsIdmSelector.constructFromObject(data['IdmSelector']);
            }
            if (data.hasOwnProperty('Label')) {
                obj['Label'] = ApiClient.convertToType(data['Label'], 'String');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('NodesSelector')) {
                obj['NodesSelector'] = JobsNodesSelector.constructFromObject(data['NodesSelector']);
            }
            if (data.hasOwnProperty('TriggerFilter')) {
                obj['TriggerFilter'] = JobsTriggerFilter.constructFromObject(data['TriggerFilter']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/JobsActionOutputFilter} ActionOutputFilter
 */
EntSelectorTemplate.prototype['ActionOutputFilter'] = undefined;

/**
 * @member {Boolean} AsFilter
 */
EntSelectorTemplate.prototype['AsFilter'] = undefined;

/**
 * @member {module:model/JobsContextMetaFilter} ContextMetaFilter
 */
EntSelectorTemplate.prototype['ContextMetaFilter'] = undefined;

/**
 * @member {module:model/JobsDataSourceSelector} DataSourceSelector
 */
EntSelectorTemplate.prototype['DataSourceSelector'] = undefined;

/**
 * @member {String} Description
 */
EntSelectorTemplate.prototype['Description'] = undefined;

/**
 * @member {module:model/JobsIdmSelector} IdmSelector
 */
EntSelectorTemplate.prototype['IdmSelector'] = undefined;

/**
 * @member {String} Label
 */
EntSelectorTemplate.prototype['Label'] = undefined;

/**
 * @member {String} Name
 */
EntSelectorTemplate.prototype['Name'] = undefined;

/**
 * @member {module:model/JobsNodesSelector} NodesSelector
 */
EntSelectorTemplate.prototype['NodesSelector'] = undefined;

/**
 * @member {module:model/JobsTriggerFilter} TriggerFilter
 */
EntSelectorTemplate.prototype['TriggerFilter'] = undefined;






export default EntSelectorTemplate;

