/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuthLdapServerConfig from './AuthLdapServerConfig';
import AuthOAuth2ConnectorBitbucketConfig from './AuthOAuth2ConnectorBitbucketConfig';
import AuthOAuth2ConnectorGithubConfig from './AuthOAuth2ConnectorGithubConfig';
import AuthOAuth2ConnectorGitlabConfig from './AuthOAuth2ConnectorGitlabConfig';
import AuthOAuth2ConnectorLinkedinConfig from './AuthOAuth2ConnectorLinkedinConfig';
import AuthOAuth2ConnectorMicrosoftConfig from './AuthOAuth2ConnectorMicrosoftConfig';
import AuthOAuth2ConnectorOAuthConfig from './AuthOAuth2ConnectorOAuthConfig';
import AuthOAuth2ConnectorOIDCConfig from './AuthOAuth2ConnectorOIDCConfig';
import AuthOAuth2ConnectorPydioConfig from './AuthOAuth2ConnectorPydioConfig';
import AuthOAuth2ConnectorSAMLConfig from './AuthOAuth2ConnectorSAMLConfig';
import AuthOAuth2MappingRule from './AuthOAuth2MappingRule';

/**
 * The InlineObject1 model module.
 * @module model/InlineObject1
 * @version 2.0
 */
class InlineObject1 {
    /**
     * Constructs a new <code>InlineObject1</code>.
     * @alias module:model/InlineObject1
     */
    constructor() { 
        
        InlineObject1.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject1} obj Optional instance to populate.
     * @return {module:model/InlineObject1} The populated <code>InlineObject1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject1();

            if (data.hasOwnProperty('configbitbucket')) {
                obj['configbitbucket'] = AuthOAuth2ConnectorBitbucketConfig.constructFromObject(data['configbitbucket']);
            }
            if (data.hasOwnProperty('configgithub')) {
                obj['configgithub'] = AuthOAuth2ConnectorGithubConfig.constructFromObject(data['configgithub']);
            }
            if (data.hasOwnProperty('configgitlab')) {
                obj['configgitlab'] = AuthOAuth2ConnectorGitlabConfig.constructFromObject(data['configgitlab']);
            }
            if (data.hasOwnProperty('configldap')) {
                obj['configldap'] = AuthLdapServerConfig.constructFromObject(data['configldap']);
            }
            if (data.hasOwnProperty('configlinkedin')) {
                obj['configlinkedin'] = AuthOAuth2ConnectorLinkedinConfig.constructFromObject(data['configlinkedin']);
            }
            if (data.hasOwnProperty('configmicrosoft')) {
                obj['configmicrosoft'] = AuthOAuth2ConnectorMicrosoftConfig.constructFromObject(data['configmicrosoft']);
            }
            if (data.hasOwnProperty('configoauth')) {
                obj['configoauth'] = AuthOAuth2ConnectorOAuthConfig.constructFromObject(data['configoauth']);
            }
            if (data.hasOwnProperty('configoidc')) {
                obj['configoidc'] = AuthOAuth2ConnectorOIDCConfig.constructFromObject(data['configoidc']);
            }
            if (data.hasOwnProperty('configpydio')) {
                obj['configpydio'] = AuthOAuth2ConnectorPydioConfig.constructFromObject(data['configpydio']);
            }
            if (data.hasOwnProperty('configsaml')) {
                obj['configsaml'] = AuthOAuth2ConnectorSAMLConfig.constructFromObject(data['configsaml']);
            }
            if (data.hasOwnProperty('mappingRules')) {
                obj['mappingRules'] = ApiClient.convertToType(data['mappingRules'], [AuthOAuth2MappingRule]);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('sites')) {
                obj['sites'] = ApiClient.convertToType(data['sites'], ['String']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AuthOAuth2ConnectorBitbucketConfig} configbitbucket
 */
InlineObject1.prototype['configbitbucket'] = undefined;

/**
 * @member {module:model/AuthOAuth2ConnectorGithubConfig} configgithub
 */
InlineObject1.prototype['configgithub'] = undefined;

/**
 * @member {module:model/AuthOAuth2ConnectorGitlabConfig} configgitlab
 */
InlineObject1.prototype['configgitlab'] = undefined;

/**
 * @member {module:model/AuthLdapServerConfig} configldap
 */
InlineObject1.prototype['configldap'] = undefined;

/**
 * @member {module:model/AuthOAuth2ConnectorLinkedinConfig} configlinkedin
 */
InlineObject1.prototype['configlinkedin'] = undefined;

/**
 * @member {module:model/AuthOAuth2ConnectorMicrosoftConfig} configmicrosoft
 */
InlineObject1.prototype['configmicrosoft'] = undefined;

/**
 * @member {module:model/AuthOAuth2ConnectorOAuthConfig} configoauth
 */
InlineObject1.prototype['configoauth'] = undefined;

/**
 * @member {module:model/AuthOAuth2ConnectorOIDCConfig} configoidc
 */
InlineObject1.prototype['configoidc'] = undefined;

/**
 * @member {module:model/AuthOAuth2ConnectorPydioConfig} configpydio
 */
InlineObject1.prototype['configpydio'] = undefined;

/**
 * @member {module:model/AuthOAuth2ConnectorSAMLConfig} configsaml
 */
InlineObject1.prototype['configsaml'] = undefined;

/**
 * @member {Array.<module:model/AuthOAuth2MappingRule>} mappingRules
 */
InlineObject1.prototype['mappingRules'] = undefined;

/**
 * @member {String} name
 */
InlineObject1.prototype['name'] = undefined;

/**
 * @member {Array.<String>} sites
 */
InlineObject1.prototype['sites'] = undefined;

/**
 * @member {String} type
 */
InlineObject1.prototype['type'] = undefined;






export default InlineObject1;

