/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TreeVersioningKeepPeriod from './TreeVersioningKeepPeriod';
import TreeVersioningNodeDeletedStrategy from './TreeVersioningNodeDeletedStrategy';

/**
 * The InlineObject2 model module.
 * @module model/InlineObject2
 * @version 2.0
 */
class InlineObject2 {
    /**
     * Constructs a new <code>InlineObject2</code>.
     * @alias module:model/InlineObject2
     */
    constructor() { 
        
        InlineObject2.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject2} obj Optional instance to populate.
     * @return {module:model/InlineObject2} The populated <code>InlineObject2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject2();

            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
            if (data.hasOwnProperty('IgnoreFilesGreaterThan')) {
                obj['IgnoreFilesGreaterThan'] = ApiClient.convertToType(data['IgnoreFilesGreaterThan'], 'String');
            }
            if (data.hasOwnProperty('KeepPeriods')) {
                obj['KeepPeriods'] = ApiClient.convertToType(data['KeepPeriods'], [TreeVersioningKeepPeriod]);
            }
            if (data.hasOwnProperty('MaxSizePerFile')) {
                obj['MaxSizePerFile'] = ApiClient.convertToType(data['MaxSizePerFile'], 'String');
            }
            if (data.hasOwnProperty('MaxTotalSize')) {
                obj['MaxTotalSize'] = ApiClient.convertToType(data['MaxTotalSize'], 'String');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('NodeDeletedStrategy')) {
                obj['NodeDeletedStrategy'] = TreeVersioningNodeDeletedStrategy.constructFromObject(data['NodeDeletedStrategy']);
            }
            if (data.hasOwnProperty('VersionsDataSourceBucket')) {
                obj['VersionsDataSourceBucket'] = ApiClient.convertToType(data['VersionsDataSourceBucket'], 'String');
            }
            if (data.hasOwnProperty('VersionsDataSourceName')) {
                obj['VersionsDataSourceName'] = ApiClient.convertToType(data['VersionsDataSourceName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} Description
 */
InlineObject2.prototype['Description'] = undefined;

/**
 * @member {String} IgnoreFilesGreaterThan
 */
InlineObject2.prototype['IgnoreFilesGreaterThan'] = undefined;

/**
 * @member {Array.<module:model/TreeVersioningKeepPeriod>} KeepPeriods
 */
InlineObject2.prototype['KeepPeriods'] = undefined;

/**
 * @member {String} MaxSizePerFile
 */
InlineObject2.prototype['MaxSizePerFile'] = undefined;

/**
 * @member {String} MaxTotalSize
 */
InlineObject2.prototype['MaxTotalSize'] = undefined;

/**
 * @member {String} Name
 */
InlineObject2.prototype['Name'] = undefined;

/**
 * @member {module:model/TreeVersioningNodeDeletedStrategy} NodeDeletedStrategy
 */
InlineObject2.prototype['NodeDeletedStrategy'] = undefined;

/**
 * @member {String} VersionsDataSourceBucket
 */
InlineObject2.prototype['VersionsDataSourceBucket'] = undefined;

/**
 * @member {String} VersionsDataSourceName
 */
InlineObject2.prototype['VersionsDataSourceName'] = undefined;






export default InlineObject2;

