/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IpbanIPsCollection model module.
 * @module model/IpbanIPsCollection
 * @version 2.0
 */
class IpbanIPsCollection {
    /**
     * Constructs a new <code>IpbanIPsCollection</code>.
     * @alias module:model/IpbanIPsCollection
     */
    constructor() { 
        
        IpbanIPsCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IpbanIPsCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IpbanIPsCollection} obj Optional instance to populate.
     * @return {module:model/IpbanIPsCollection} The populated <code>IpbanIPsCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IpbanIPsCollection();

            if (data.hasOwnProperty('IPs')) {
                obj['IPs'] = ApiClient.convertToType(data['IPs'], ['String']);
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} IPs
 */
IpbanIPsCollection.prototype['IPs'] = undefined;

/**
 * @member {String} Name
 */
IpbanIPsCollection.prototype['Name'] = undefined;






export default IpbanIPsCollection;

