/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The IpbanIPsCollection model module.
* @module model/IpbanIPsCollection
* @version 2.0
*/
export default class IpbanIPsCollection {
    /**
    * Constructs a new <code>IpbanIPsCollection</code>.
    * @alias module:model/IpbanIPsCollection
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>IpbanIPsCollection</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IpbanIPsCollection} obj Optional instance to populate.
    * @return {module:model/IpbanIPsCollection} The populated <code>IpbanIPsCollection</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IpbanIPsCollection();

            
            
            

            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('IPs')) {
                obj['IPs'] = ApiClient.convertToType(data['IPs'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} Name
    */
    Name = undefined;
    /**
    * @member {Array.<String>} IPs
    */
    IPs = undefined;








}


