/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IpbanConnectionAttempt from './IpbanConnectionAttempt';

/**
 * The IpbanBannedConnection model module.
 * @module model/IpbanBannedConnection
 * @version 2.0
 */
class IpbanBannedConnection {
    /**
     * Constructs a new <code>IpbanBannedConnection</code>.
     * @alias module:model/IpbanBannedConnection
     */
    constructor() { 
        
        IpbanBannedConnection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IpbanBannedConnection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IpbanBannedConnection} obj Optional instance to populate.
     * @return {module:model/IpbanBannedConnection} The populated <code>IpbanBannedConnection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IpbanBannedConnection();

            if (data.hasOwnProperty('BanExpire')) {
                obj['BanExpire'] = ApiClient.convertToType(data['BanExpire'], 'String');
            }
            if (data.hasOwnProperty('History')) {
                obj['History'] = ApiClient.convertToType(data['History'], [IpbanConnectionAttempt]);
            }
            if (data.hasOwnProperty('IP')) {
                obj['IP'] = ApiClient.convertToType(data['IP'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} BanExpire
 */
IpbanBannedConnection.prototype['BanExpire'] = undefined;

/**
 * @member {Array.<module:model/IpbanConnectionAttempt>} History
 */
IpbanBannedConnection.prototype['History'] = undefined;

/**
 * @member {String} IP
 */
IpbanBannedConnection.prototype['IP'] = undefined;






export default IpbanBannedConnection;

