/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The JobsDeleteJobResponse model module.
* @module model/JobsDeleteJobResponse
* @version 2.0
*/
export default class JobsDeleteJobResponse {
    /**
    * Constructs a new <code>JobsDeleteJobResponse</code>.
    * @alias module:model/JobsDeleteJobResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>JobsDeleteJobResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/JobsDeleteJobResponse} obj Optional instance to populate.
    * @return {module:model/JobsDeleteJobResponse} The populated <code>JobsDeleteJobResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobsDeleteJobResponse();

            
            
            

            if (data.hasOwnProperty('Success')) {
                obj['Success'] = ApiClient.convertToType(data['Success'], 'Boolean');
            }
            if (data.hasOwnProperty('DeleteCount')) {
                obj['DeleteCount'] = ApiClient.convertToType(data['DeleteCount'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} Success
    */
    Success = undefined;
    /**
    * @member {Number} DeleteCount
    */
    DeleteCount = undefined;








}


