/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LogTimeRangeResult model module.
 * @module model/LogTimeRangeResult
 * @version 2.0
 */
class LogTimeRangeResult {
    /**
     * Constructs a new <code>LogTimeRangeResult</code>.
     * TimeRangeResult represents one point of a graph.
     * @alias module:model/LogTimeRangeResult
     */
    constructor() { 
        
        LogTimeRangeResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LogTimeRangeResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LogTimeRangeResult} obj Optional instance to populate.
     * @return {module:model/LogTimeRangeResult} The populated <code>LogTimeRangeResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LogTimeRangeResult();

            if (data.hasOwnProperty('Count')) {
                obj['Count'] = ApiClient.convertToType(data['Count'], 'Number');
            }
            if (data.hasOwnProperty('End')) {
                obj['End'] = ApiClient.convertToType(data['End'], 'Number');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('Relevance')) {
                obj['Relevance'] = ApiClient.convertToType(data['Relevance'], 'Number');
            }
            if (data.hasOwnProperty('Start')) {
                obj['Start'] = ApiClient.convertToType(data['Start'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} Count
 */
LogTimeRangeResult.prototype['Count'] = undefined;

/**
 * @member {Number} End
 */
LogTimeRangeResult.prototype['End'] = undefined;

/**
 * @member {String} Name
 */
LogTimeRangeResult.prototype['Name'] = undefined;

/**
 * @member {Number} Relevance
 */
LogTimeRangeResult.prototype['Relevance'] = undefined;

/**
 * @member {Number} Start
 */
LogTimeRangeResult.prototype['Start'] = undefined;






export default LogTimeRangeResult;

