/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReportsAuditedWorkspace from './ReportsAuditedWorkspace';
import TreeNode from './TreeNode';

/**
 * The ReportsSharedResource model module.
 * @module model/ReportsSharedResource
 * @version 2.0
 */
class ReportsSharedResource {
    /**
     * Constructs a new <code>ReportsSharedResource</code>.
     * @alias module:model/ReportsSharedResource
     */
    constructor() { 
        
        ReportsSharedResource.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportsSharedResource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportsSharedResource} obj Optional instance to populate.
     * @return {module:model/ReportsSharedResource} The populated <code>ReportsSharedResource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportsSharedResource();

            if (data.hasOwnProperty('ChildrenSharedResources')) {
                obj['ChildrenSharedResources'] = ApiClient.convertToType(data['ChildrenSharedResources'], 'Number');
            }
            if (data.hasOwnProperty('Node')) {
                obj['Node'] = TreeNode.constructFromObject(data['Node']);
            }
            if (data.hasOwnProperty('ReportDate')) {
                obj['ReportDate'] = ApiClient.convertToType(data['ReportDate'], 'Number');
            }
            if (data.hasOwnProperty('Workspaces')) {
                obj['Workspaces'] = ApiClient.convertToType(data['Workspaces'], [ReportsAuditedWorkspace]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} ChildrenSharedResources
 */
ReportsSharedResource.prototype['ChildrenSharedResources'] = undefined;

/**
 * @member {module:model/TreeNode} Node
 */
ReportsSharedResource.prototype['Node'] = undefined;

/**
 * @member {Number} ReportDate
 */
ReportsSharedResource.prototype['ReportDate'] = undefined;

/**
 * @member {Array.<module:model/ReportsAuditedWorkspace>} Workspaces
 */
ReportsSharedResource.prototype['Workspaces'] = undefined;






export default ReportsSharedResource;

