/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReportsSharedResourceShareType from './ReportsSharedResourceShareType';
import TreeNodeType from './TreeNodeType';

/**
 * The ReportsSharedResourcesRequest model module.
 * @module model/ReportsSharedResourcesRequest
 * @version 2.0
 */
class ReportsSharedResourcesRequest {
    /**
     * Constructs a new <code>ReportsSharedResourcesRequest</code>.
     * @alias module:model/ReportsSharedResourcesRequest
     */
    constructor() { 
        
        ReportsSharedResourcesRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportsSharedResourcesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportsSharedResourcesRequest} obj Optional instance to populate.
     * @return {module:model/ReportsSharedResourcesRequest} The populated <code>ReportsSharedResourcesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportsSharedResourcesRequest();

            if (data.hasOwnProperty('LastUpdatedBefore')) {
                obj['LastUpdatedBefore'] = ApiClient.convertToType(data['LastUpdatedBefore'], 'Number');
            }
            if (data.hasOwnProperty('LastUpdatedSince')) {
                obj['LastUpdatedSince'] = ApiClient.convertToType(data['LastUpdatedSince'], 'Number');
            }
            if (data.hasOwnProperty('Limit')) {
                obj['Limit'] = ApiClient.convertToType(data['Limit'], 'Number');
            }
            if (data.hasOwnProperty('NodeSizeMin')) {
                obj['NodeSizeMin'] = ApiClient.convertToType(data['NodeSizeMin'], 'Number');
            }
            if (data.hasOwnProperty('NodeType')) {
                obj['NodeType'] = TreeNodeType.constructFromObject(data['NodeType']);
            }
            if (data.hasOwnProperty('Offset')) {
                obj['Offset'] = ApiClient.convertToType(data['Offset'], 'Number');
            }
            if (data.hasOwnProperty('OwnerUUID')) {
                obj['OwnerUUID'] = ApiClient.convertToType(data['OwnerUUID'], 'String');
            }
            if (data.hasOwnProperty('RolesReadAND')) {
                obj['RolesReadAND'] = ApiClient.convertToType(data['RolesReadAND'], 'Boolean');
            }
            if (data.hasOwnProperty('RolesReadUUIDs')) {
                obj['RolesReadUUIDs'] = ApiClient.convertToType(data['RolesReadUUIDs'], ['String']);
            }
            if (data.hasOwnProperty('RootPath')) {
                obj['RootPath'] = ApiClient.convertToType(data['RootPath'], 'String');
            }
            if (data.hasOwnProperty('ShareType')) {
                obj['ShareType'] = ReportsSharedResourceShareType.constructFromObject(data['ShareType']);
            }
            if (data.hasOwnProperty('UsersReadCountMax')) {
                obj['UsersReadCountMax'] = ApiClient.convertToType(data['UsersReadCountMax'], 'Number');
            }
            if (data.hasOwnProperty('UsersReadCountMin')) {
                obj['UsersReadCountMin'] = ApiClient.convertToType(data['UsersReadCountMin'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} LastUpdatedBefore
 */
ReportsSharedResourcesRequest.prototype['LastUpdatedBefore'] = undefined;

/**
 * @member {Number} LastUpdatedSince
 */
ReportsSharedResourcesRequest.prototype['LastUpdatedSince'] = undefined;

/**
 * @member {Number} Limit
 */
ReportsSharedResourcesRequest.prototype['Limit'] = undefined;

/**
 * @member {Number} NodeSizeMin
 */
ReportsSharedResourcesRequest.prototype['NodeSizeMin'] = undefined;

/**
 * @member {module:model/TreeNodeType} NodeType
 */
ReportsSharedResourcesRequest.prototype['NodeType'] = undefined;

/**
 * @member {Number} Offset
 */
ReportsSharedResourcesRequest.prototype['Offset'] = undefined;

/**
 * @member {String} OwnerUUID
 */
ReportsSharedResourcesRequest.prototype['OwnerUUID'] = undefined;

/**
 * @member {Boolean} RolesReadAND
 */
ReportsSharedResourcesRequest.prototype['RolesReadAND'] = undefined;

/**
 * @member {Array.<String>} RolesReadUUIDs
 */
ReportsSharedResourcesRequest.prototype['RolesReadUUIDs'] = undefined;

/**
 * @member {String} RootPath
 */
ReportsSharedResourcesRequest.prototype['RootPath'] = undefined;

/**
 * @member {module:model/ReportsSharedResourceShareType} ShareType
 */
ReportsSharedResourcesRequest.prototype['ShareType'] = undefined;

/**
 * @member {Number} UsersReadCountMax
 */
ReportsSharedResourcesRequest.prototype['UsersReadCountMax'] = undefined;

/**
 * @member {Number} UsersReadCountMin
 */
ReportsSharedResourcesRequest.prototype['UsersReadCountMin'] = undefined;






export default ReportsSharedResourcesRequest;

