/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ReportsSharedResource from './ReportsSharedResource';





/**
* The ReportsSharedResourcesResponse model module.
* @module model/ReportsSharedResourcesResponse
* @version 2.0
*/
export default class ReportsSharedResourcesResponse {
    /**
    * Constructs a new <code>ReportsSharedResourcesResponse</code>.
    * @alias module:model/ReportsSharedResourcesResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ReportsSharedResourcesResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ReportsSharedResourcesResponse} obj Optional instance to populate.
    * @return {module:model/ReportsSharedResourcesResponse} The populated <code>ReportsSharedResourcesResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportsSharedResourcesResponse();

            
            
            

            if (data.hasOwnProperty('Resources')) {
                obj['Resources'] = ApiClient.convertToType(data['Resources'], [ReportsSharedResource]);
            }
            if (data.hasOwnProperty('Offset')) {
                obj['Offset'] = ApiClient.convertToType(data['Offset'], 'Number');
            }
            if (data.hasOwnProperty('Limit')) {
                obj['Limit'] = ApiClient.convertToType(data['Limit'], 'Number');
            }
            if (data.hasOwnProperty('Total')) {
                obj['Total'] = ApiClient.convertToType(data['Total'], 'Number');
            }
            if (data.hasOwnProperty('Facets')) {
                obj['Facets'] = ApiClient.convertToType(data['Facets'], {'String': 'Number'});
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/ReportsSharedResource>} Resources
    */
    Resources = undefined;
    /**
    * @member {Number} Offset
    */
    Offset = undefined;
    /**
    * @member {Number} Limit
    */
    Limit = undefined;
    /**
    * @member {Number} Total
    */
    Total = undefined;
    /**
    * @member {Object.<String, Number>} Facets
    */
    Facets = undefined;








}


