/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ReportsAuditedWorkspace from './ReportsAuditedWorkspace';
import TreeNode from './TreeNode';





/**
* The ReportsSharedResource model module.
* @module model/ReportsSharedResource
* @version 2.0
*/
export default class ReportsSharedResource {
    /**
    * Constructs a new <code>ReportsSharedResource</code>.
    * @alias module:model/ReportsSharedResource
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ReportsSharedResource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ReportsSharedResource} obj Optional instance to populate.
    * @return {module:model/ReportsSharedResource} The populated <code>ReportsSharedResource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportsSharedResource();

            
            
            

            if (data.hasOwnProperty('Node')) {
                obj['Node'] = TreeNode.constructFromObject(data['Node']);
            }
            if (data.hasOwnProperty('Workspaces')) {
                obj['Workspaces'] = ApiClient.convertToType(data['Workspaces'], [ReportsAuditedWorkspace]);
            }
            if (data.hasOwnProperty('ChildrenSharedResources')) {
                obj['ChildrenSharedResources'] = ApiClient.convertToType(data['ChildrenSharedResources'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/TreeNode} Node
    */
    Node = undefined;
    /**
    * @member {Array.<module:model/ReportsAuditedWorkspace>} Workspaces
    */
    Workspaces = undefined;
    /**
    * @member {Number} ChildrenSharedResources
    */
    ChildrenSharedResources = undefined;








}


