/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReportsSharedResource from './ReportsSharedResource';

/**
 * The ReportsSharedResourcesResponse model module.
 * @module model/ReportsSharedResourcesResponse
 * @version 2.0
 */
class ReportsSharedResourcesResponse {
    /**
     * Constructs a new <code>ReportsSharedResourcesResponse</code>.
     * @alias module:model/ReportsSharedResourcesResponse
     */
    constructor() { 
        
        ReportsSharedResourcesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportsSharedResourcesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportsSharedResourcesResponse} obj Optional instance to populate.
     * @return {module:model/ReportsSharedResourcesResponse} The populated <code>ReportsSharedResourcesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportsSharedResourcesResponse();

            if (data.hasOwnProperty('Facets')) {
                obj['Facets'] = ApiClient.convertToType(data['Facets'], {'String': 'Number'});
            }
            if (data.hasOwnProperty('Limit')) {
                obj['Limit'] = ApiClient.convertToType(data['Limit'], 'Number');
            }
            if (data.hasOwnProperty('Offset')) {
                obj['Offset'] = ApiClient.convertToType(data['Offset'], 'Number');
            }
            if (data.hasOwnProperty('Resources')) {
                obj['Resources'] = ApiClient.convertToType(data['Resources'], [ReportsSharedResource]);
            }
            if (data.hasOwnProperty('Total')) {
                obj['Total'] = ApiClient.convertToType(data['Total'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Number>} Facets
 */
ReportsSharedResourcesResponse.prototype['Facets'] = undefined;

/**
 * @member {Number} Limit
 */
ReportsSharedResourcesResponse.prototype['Limit'] = undefined;

/**
 * @member {Number} Offset
 */
ReportsSharedResourcesResponse.prototype['Offset'] = undefined;

/**
 * @member {Array.<module:model/ReportsSharedResource>} Resources
 */
ReportsSharedResourcesResponse.prototype['Resources'] = undefined;

/**
 * @member {Number} Total
 */
ReportsSharedResourcesResponse.prototype['Total'] = undefined;






export default ReportsSharedResourcesResponse;

