/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReportsListReportsResponse model module.
 * @module model/ReportsListReportsResponse
 * @version 2.0
 */
class ReportsListReportsResponse {
    /**
     * Constructs a new <code>ReportsListReportsResponse</code>.
     * @alias module:model/ReportsListReportsResponse
     */
    constructor() { 
        
        ReportsListReportsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportsListReportsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportsListReportsResponse} obj Optional instance to populate.
     * @return {module:model/ReportsListReportsResponse} The populated <code>ReportsListReportsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportsListReportsResponse();

            if (data.hasOwnProperty('ReportDates')) {
                obj['ReportDates'] = ApiClient.convertToType(data['ReportDates'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} ReportDates
 */
ReportsListReportsResponse.prototype['ReportDates'] = undefined;






export default ReportsListReportsResponse;

