/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdmRole from './IdmRole';
import IdmUser from './IdmUser';
import IdmWorkspace from './IdmWorkspace';

/**
 * The ReportsAuditedWorkspace model module.
 * @module model/ReportsAuditedWorkspace
 * @version 2.0
 */
class ReportsAuditedWorkspace {
    /**
     * Constructs a new <code>ReportsAuditedWorkspace</code>.
     * @alias module:model/ReportsAuditedWorkspace
     */
    constructor() { 
        
        ReportsAuditedWorkspace.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportsAuditedWorkspace</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportsAuditedWorkspace} obj Optional instance to populate.
     * @return {module:model/ReportsAuditedWorkspace} The populated <code>ReportsAuditedWorkspace</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportsAuditedWorkspace();

            if (data.hasOwnProperty('BrokenLink')) {
                obj['BrokenLink'] = ApiClient.convertToType(data['BrokenLink'], 'Boolean');
            }
            if (data.hasOwnProperty('OwnerUser')) {
                obj['OwnerUser'] = IdmUser.constructFromObject(data['OwnerUser']);
            }
            if (data.hasOwnProperty('RolesRead')) {
                obj['RolesRead'] = ApiClient.convertToType(data['RolesRead'], [IdmRole]);
            }
            if (data.hasOwnProperty('RolesWrite')) {
                obj['RolesWrite'] = ApiClient.convertToType(data['RolesWrite'], [IdmRole]);
            }
            if (data.hasOwnProperty('UsersReadCount')) {
                obj['UsersReadCount'] = ApiClient.convertToType(data['UsersReadCount'], 'Number');
            }
            if (data.hasOwnProperty('UsersWriteCount')) {
                obj['UsersWriteCount'] = ApiClient.convertToType(data['UsersWriteCount'], 'Number');
            }
            if (data.hasOwnProperty('Workspace')) {
                obj['Workspace'] = IdmWorkspace.constructFromObject(data['Workspace']);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} BrokenLink
 */
ReportsAuditedWorkspace.prototype['BrokenLink'] = undefined;

/**
 * @member {module:model/IdmUser} OwnerUser
 */
ReportsAuditedWorkspace.prototype['OwnerUser'] = undefined;

/**
 * @member {Array.<module:model/IdmRole>} RolesRead
 */
ReportsAuditedWorkspace.prototype['RolesRead'] = undefined;

/**
 * @member {Array.<module:model/IdmRole>} RolesWrite
 */
ReportsAuditedWorkspace.prototype['RolesWrite'] = undefined;

/**
 * @member {Number} UsersReadCount
 */
ReportsAuditedWorkspace.prototype['UsersReadCount'] = undefined;

/**
 * @member {Number} UsersWriteCount
 */
ReportsAuditedWorkspace.prototype['UsersWriteCount'] = undefined;

/**
 * @member {module:model/IdmWorkspace} Workspace
 */
ReportsAuditedWorkspace.prototype['Workspace'] = undefined;






export default ReportsAuditedWorkspace;

