/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LogTimeRangeCursor from './LogTimeRangeCursor';
import LogTimeRangeResult from './LogTimeRangeResult';

/**
 * The RestTimeRangeResultCollection model module.
 * @module model/RestTimeRangeResultCollection
 * @version 2.0
 */
class RestTimeRangeResultCollection {
    /**
     * Constructs a new <code>RestTimeRangeResultCollection</code>.
     * @alias module:model/RestTimeRangeResultCollection
     */
    constructor() { 
        
        RestTimeRangeResultCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestTimeRangeResultCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestTimeRangeResultCollection} obj Optional instance to populate.
     * @return {module:model/RestTimeRangeResultCollection} The populated <code>RestTimeRangeResultCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestTimeRangeResultCollection();

            if (data.hasOwnProperty('Links')) {
                obj['Links'] = ApiClient.convertToType(data['Links'], [LogTimeRangeCursor]);
            }
            if (data.hasOwnProperty('Results')) {
                obj['Results'] = ApiClient.convertToType(data['Results'], [LogTimeRangeResult]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/LogTimeRangeCursor>} Links
 */
RestTimeRangeResultCollection.prototype['Links'] = undefined;

/**
 * @member {Array.<module:model/LogTimeRangeResult>} Results
 */
RestTimeRangeResultCollection.prototype['Results'] = undefined;






export default RestTimeRangeResultCollection;

