/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthOAuth2ConnectorCollection from '../model/AuthOAuth2ConnectorCollection';
import EntDeleteVersioningPolicyResponse from '../model/EntDeleteVersioningPolicyResponse';
import EntDeleteVirtualNodeResponse from '../model/EntDeleteVirtualNodeResponse';
import EntExternalDirectoryCollection from '../model/EntExternalDirectoryCollection';
import EntExternalDirectoryConfig from '../model/EntExternalDirectoryConfig';
import EntExternalDirectoryPingRequest from '../model/EntExternalDirectoryPingRequest';
import EntExternalDirectoryResponse from '../model/EntExternalDirectoryResponse';
import EntExternalDirectorySearchRequest from '../model/EntExternalDirectorySearchRequest';
import EntExternalDirectoryTestResponse from '../model/EntExternalDirectoryTestResponse';
import EntListSitesResponse from '../model/EntListSitesResponse';
import EntOAuth2ClientCollection from '../model/EntOAuth2ClientCollection';
import EntOAuth2ClientResponse from '../model/EntOAuth2ClientResponse';
import EntOAuth2ConnectorCollection from '../model/EntOAuth2ConnectorCollection';
import EntOAuth2ConnectorResponse from '../model/EntOAuth2ConnectorResponse';
import InlineObject from '../model/InlineObject';
import InlineObject1 from '../model/InlineObject1';
import InlineObject2 from '../model/InlineObject2';
import InlineObject3 from '../model/InlineObject3';
import RpcStatus from '../model/RpcStatus';
import TreeNode from '../model/TreeNode';
import TreeVersioningPolicy from '../model/TreeVersioningPolicy';

/**
* EnterpriseConfigService service.
* @module api/EnterpriseConfigServiceApi
* @version 2.0
*/
export default class EnterpriseConfigServiceApi {

    /**
    * Constructs a new EnterpriseConfigServiceApi. 
    * @alias module:api/EnterpriseConfigServiceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * [Enterprise Only] Delete external directory
     * @param {String} configId Id of the external directory
     * @param {Object} opts Optional parameters
     * @param {String} opts.configConfigId 
     * @param {String} opts.configDomainName 
     * @param {String} opts.configHost 
     * @param {String} opts.configConnection 
     * @param {String} opts.configBindDN 
     * @param {String} opts.configBindPW 
     * @param {Boolean} opts.configBindAnonymous 
     * @param {Boolean} opts.configSkipVerifyCertificate 
     * @param {String} opts.configRootCA 
     * @param {String} opts.configRootCAData To be converted to []byte
     * @param {Number} opts.configPageSize 
     * @param {Array.<String>} opts.configUserDNs 
     * @param {String} opts.configUserFilter 
     * @param {String} opts.configUserIDAttribute 
     * @param {String} opts.configUserDisplayAttribute 
     * @param {String} opts.configUserScope 
     * @param {String} opts.configMemberOfMappingMappingLeftAttribute 
     * @param {String} opts.configMemberOfMappingMappingRightAttribute 
     * @param {String} opts.configMemberOfMappingMappingRuleString 
     * @param {String} opts.configMemberOfMappingMappingRolePrefix 
     * @param {Array.<String>} opts.configMemberOfMappingGroupFilterDNs 
     * @param {String} opts.configMemberOfMappingGroupFilterFilter 
     * @param {String} opts.configMemberOfMappingGroupFilterIDAttribute 
     * @param {String} opts.configMemberOfMappingGroupFilterDisplayAttribute 
     * @param {String} opts.configMemberOfMappingGroupFilterScope 
     * @param {Boolean} opts.configMemberOfMappingSupportNestedGroup 
     * @param {Boolean} opts.configMemberOfMappingRealMemberOf 
     * @param {String} opts.configMemberOfMappingRealMemberOfAttribute 
     * @param {String} opts.configMemberOfMappingRealMemberOfValueFormat 
     * @param {String} opts.configMemberOfMappingPydioMemberOfAttribute 
     * @param {String} opts.configMemberOfMappingPydioMemberOfValueFormat 
     * @param {String} opts.configRolePrefix 
     * @param {String} opts.configSchedule 
     * @param {String} opts.configSchedulerDetails 
     * @param {Boolean} opts.configSyncOnly 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntExternalDirectoryResponse} and HTTP response
     */
    deleteExternalDirectoryWithHttpInfo(configId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'configId' is set
      if (configId === undefined || configId === null) {
        throw new Error("Missing the required parameter 'configId' when calling deleteExternalDirectory");
      }

      let pathParams = {
        'ConfigId': configId
      };
      let queryParams = {
        'Config.ConfigId': opts['configConfigId'],
        'Config.DomainName': opts['configDomainName'],
        'Config.Host': opts['configHost'],
        'Config.Connection': opts['configConnection'],
        'Config.BindDN': opts['configBindDN'],
        'Config.BindPW': opts['configBindPW'],
        'Config.BindAnonymous': opts['configBindAnonymous'],
        'Config.SkipVerifyCertificate': opts['configSkipVerifyCertificate'],
        'Config.RootCA': opts['configRootCA'],
        'Config.RootCAData': opts['configRootCAData'],
        'Config.PageSize': opts['configPageSize'],
        'Config.User.DNs': this.apiClient.buildCollectionParam(opts['configUserDNs'], 'multi'),
        'Config.User.Filter': opts['configUserFilter'],
        'Config.User.IDAttribute': opts['configUserIDAttribute'],
        'Config.User.DisplayAttribute': opts['configUserDisplayAttribute'],
        'Config.User.Scope': opts['configUserScope'],
        'Config.MemberOfMapping.Mapping.LeftAttribute': opts['configMemberOfMappingMappingLeftAttribute'],
        'Config.MemberOfMapping.Mapping.RightAttribute': opts['configMemberOfMappingMappingRightAttribute'],
        'Config.MemberOfMapping.Mapping.RuleString': opts['configMemberOfMappingMappingRuleString'],
        'Config.MemberOfMapping.Mapping.RolePrefix': opts['configMemberOfMappingMappingRolePrefix'],
        'Config.MemberOfMapping.GroupFilter.DNs': this.apiClient.buildCollectionParam(opts['configMemberOfMappingGroupFilterDNs'], 'multi'),
        'Config.MemberOfMapping.GroupFilter.Filter': opts['configMemberOfMappingGroupFilterFilter'],
        'Config.MemberOfMapping.GroupFilter.IDAttribute': opts['configMemberOfMappingGroupFilterIDAttribute'],
        'Config.MemberOfMapping.GroupFilter.DisplayAttribute': opts['configMemberOfMappingGroupFilterDisplayAttribute'],
        'Config.MemberOfMapping.GroupFilter.Scope': opts['configMemberOfMappingGroupFilterScope'],
        'Config.MemberOfMapping.SupportNestedGroup': opts['configMemberOfMappingSupportNestedGroup'],
        'Config.MemberOfMapping.RealMemberOf': opts['configMemberOfMappingRealMemberOf'],
        'Config.MemberOfMapping.RealMemberOfAttribute': opts['configMemberOfMappingRealMemberOfAttribute'],
        'Config.MemberOfMapping.RealMemberOfValueFormat': opts['configMemberOfMappingRealMemberOfValueFormat'],
        'Config.MemberOfMapping.PydioMemberOfAttribute': opts['configMemberOfMappingPydioMemberOfAttribute'],
        'Config.MemberOfMapping.PydioMemberOfValueFormat': opts['configMemberOfMappingPydioMemberOfValueFormat'],
        'Config.RolePrefix': opts['configRolePrefix'],
        'Config.Schedule': opts['configSchedule'],
        'Config.SchedulerDetails': opts['configSchedulerDetails'],
        'Config.SyncOnly': opts['configSyncOnly']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EntExternalDirectoryResponse;
      return this.apiClient.callApi(
        '/config/directories/{ConfigId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] Delete external directory
     * @param {String} configId Id of the external directory
     * @param {Object} opts Optional parameters
     * @param {String} opts.configConfigId 
     * @param {String} opts.configDomainName 
     * @param {String} opts.configHost 
     * @param {String} opts.configConnection 
     * @param {String} opts.configBindDN 
     * @param {String} opts.configBindPW 
     * @param {Boolean} opts.configBindAnonymous 
     * @param {Boolean} opts.configSkipVerifyCertificate 
     * @param {String} opts.configRootCA 
     * @param {String} opts.configRootCAData To be converted to []byte
     * @param {Number} opts.configPageSize 
     * @param {Array.<String>} opts.configUserDNs 
     * @param {String} opts.configUserFilter 
     * @param {String} opts.configUserIDAttribute 
     * @param {String} opts.configUserDisplayAttribute 
     * @param {String} opts.configUserScope 
     * @param {String} opts.configMemberOfMappingMappingLeftAttribute 
     * @param {String} opts.configMemberOfMappingMappingRightAttribute 
     * @param {String} opts.configMemberOfMappingMappingRuleString 
     * @param {String} opts.configMemberOfMappingMappingRolePrefix 
     * @param {Array.<String>} opts.configMemberOfMappingGroupFilterDNs 
     * @param {String} opts.configMemberOfMappingGroupFilterFilter 
     * @param {String} opts.configMemberOfMappingGroupFilterIDAttribute 
     * @param {String} opts.configMemberOfMappingGroupFilterDisplayAttribute 
     * @param {String} opts.configMemberOfMappingGroupFilterScope 
     * @param {Boolean} opts.configMemberOfMappingSupportNestedGroup 
     * @param {Boolean} opts.configMemberOfMappingRealMemberOf 
     * @param {String} opts.configMemberOfMappingRealMemberOfAttribute 
     * @param {String} opts.configMemberOfMappingRealMemberOfValueFormat 
     * @param {String} opts.configMemberOfMappingPydioMemberOfAttribute 
     * @param {String} opts.configMemberOfMappingPydioMemberOfValueFormat 
     * @param {String} opts.configRolePrefix 
     * @param {String} opts.configSchedule 
     * @param {String} opts.configSchedulerDetails 
     * @param {Boolean} opts.configSyncOnly 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntExternalDirectoryResponse}
     */
    deleteExternalDirectory(configId, opts) {
      return this.deleteExternalDirectoryWithHttpInfo(configId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] Delete an oauth2 client
     * @param {String} clientId 
     * @param {Object} opts Optional parameters
     * @param {String} opts.clientName 
     * @param {String} opts.clientSecret 
     * @param {Array.<String>} opts.redirectUris 
     * @param {Array.<String>} opts.grantTypes 
     * @param {Array.<String>} opts.responseTypes 
     * @param {String} opts.scope 
     * @param {Array.<String>} opts.audience 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntOAuth2ClientResponse} and HTTP response
     */
    deleteOAuth2ClientWithHttpInfo(clientId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling deleteOAuth2Client");
      }

      let pathParams = {
        'client_id': clientId
      };
      let queryParams = {
        'client_name': opts['clientName'],
        'client_secret': opts['clientSecret'],
        'redirect_uris': this.apiClient.buildCollectionParam(opts['redirectUris'], 'multi'),
        'grant_types': this.apiClient.buildCollectionParam(opts['grantTypes'], 'multi'),
        'response_types': this.apiClient.buildCollectionParam(opts['responseTypes'], 'multi'),
        'scope': opts['scope'],
        'audience': this.apiClient.buildCollectionParam(opts['audience'], 'multi')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EntOAuth2ClientResponse;
      return this.apiClient.callApi(
        '/config/oauth2clients/{client_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] Delete an oauth2 client
     * @param {String} clientId 
     * @param {Object} opts Optional parameters
     * @param {String} opts.clientName 
     * @param {String} opts.clientSecret 
     * @param {Array.<String>} opts.redirectUris 
     * @param {Array.<String>} opts.grantTypes 
     * @param {Array.<String>} opts.responseTypes 
     * @param {String} opts.scope 
     * @param {Array.<String>} opts.audience 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntOAuth2ClientResponse}
     */
    deleteOAuth2Client(clientId, opts) {
      return this.deleteOAuth2ClientWithHttpInfo(clientId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] Delete an oauth2 client
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {String} opts.type 
     * @param {String} opts.name 
     * @param {String} opts.configoidcIssuer 
     * @param {String} opts.configoidcClientID 
     * @param {String} opts.configoidcClientSecret 
     * @param {String} opts.configoidcRedirectURI 
     * @param {Boolean} opts.configoidcBasicAuthUnsupported 
     * @param {Array.<String>} opts.configoidcHostedDomains 
     * @param {Array.<String>} opts.configoidcScopes 
     * @param {Boolean} opts.configoidcInsecureSkipEmailVerified 
     * @param {Boolean} opts.configoidcGetUserInfo 
     * @param {String} opts.configoidcUserIDKey 
     * @param {String} opts.configoidcUserNameKey 
     * @param {String} opts.configsamlSsoURL 
     * @param {String} opts.configsamlCa 
     * @param {String} opts.configsamlRedirectURI 
     * @param {String} opts.configsamlUsernameAttr 
     * @param {String} opts.configsamlEmailAttr 
     * @param {String} opts.configsamlGroupsAttr 
     * @param {String} opts.configsamlCaData 
     * @param {Boolean} opts.configsamlInsecureSkipSignatureValidation 
     * @param {String} opts.configsamlEntityIssuer 
     * @param {String} opts.configsamlSsoIssuer 
     * @param {String} opts.configsamlGroupsDelim 
     * @param {String} opts.configsamlNameIDPolicyFormat 
     * @param {String} opts.configbitbucketClientID 
     * @param {String} opts.configbitbucketClientSecret 
     * @param {String} opts.configbitbucketRedirectURI 
     * @param {Array.<String>} opts.configbitbucketTeams 
     * @param {String} opts.configgithubClientID 
     * @param {String} opts.configgithubClientSecret 
     * @param {String} opts.configgithubRedirectURI 
     * @param {Boolean} opts.configgithubLoadAllGroups 
     * @param {String} opts.configgithubTeamNameField 
     * @param {Boolean} opts.configgithubUseLoginAsID 
     * @param {String} opts.configgithubHostName For GitHub enterprise
     * @param {String} opts.configgithubRootCA 
     * @param {String} opts.configgitlabBaseURL 
     * @param {String} opts.configgitlabClientID 
     * @param {String} opts.configgitlabClientSecret 
     * @param {String} opts.configgitlabRedirectURI 
     * @param {Array.<String>} opts.configgitlabGroups 
     * @param {Boolean} opts.configgitlabUserLoginAsID 
     * @param {String} opts.configlinkedinClientID 
     * @param {String} opts.configlinkedinClientSecret 
     * @param {String} opts.configlinkedinRedirectURI 
     * @param {String} opts.configmicrosoftClientID 
     * @param {String} opts.configmicrosoftClientSecret 
     * @param {String} opts.configmicrosoftRedirectURI 
     * @param {String} opts.configmicrosoftTenant 
     * @param {Array.<String>} opts.configmicrosoftGroups 
     * @param {Boolean} opts.configmicrosoftOnlySecurityGroups 
     * @param {String} opts.configmicrosoftGroupNameFormat 
     * @param {Boolean} opts.configmicrosoftUseGroupsAsWhitelist 
     * @param {String} opts.configldapConfigId 
     * @param {String} opts.configldapDomainName 
     * @param {String} opts.configldapHost 
     * @param {String} opts.configldapConnection 
     * @param {String} opts.configldapBindDN 
     * @param {String} opts.configldapBindPW 
     * @param {Boolean} opts.configldapBindAnonymous 
     * @param {Boolean} opts.configldapSkipVerifyCertificate 
     * @param {String} opts.configldapRootCA 
     * @param {String} opts.configldapRootCAData To be converted to []byte
     * @param {Number} opts.configldapPageSize 
     * @param {Array.<String>} opts.configldapUserDNs 
     * @param {String} opts.configldapUserFilter 
     * @param {String} opts.configldapUserIDAttribute 
     * @param {String} opts.configldapUserDisplayAttribute 
     * @param {String} opts.configldapUserScope 
     * @param {String} opts.configldapMemberOfMappingMappingLeftAttribute 
     * @param {String} opts.configldapMemberOfMappingMappingRightAttribute 
     * @param {String} opts.configldapMemberOfMappingMappingRuleString 
     * @param {String} opts.configldapMemberOfMappingMappingRolePrefix 
     * @param {Array.<String>} opts.configldapMemberOfMappingGroupFilterDNs 
     * @param {String} opts.configldapMemberOfMappingGroupFilterFilter 
     * @param {String} opts.configldapMemberOfMappingGroupFilterIDAttribute 
     * @param {String} opts.configldapMemberOfMappingGroupFilterDisplayAttribute 
     * @param {String} opts.configldapMemberOfMappingGroupFilterScope 
     * @param {Boolean} opts.configldapMemberOfMappingSupportNestedGroup 
     * @param {Boolean} opts.configldapMemberOfMappingRealMemberOf 
     * @param {String} opts.configldapMemberOfMappingRealMemberOfAttribute 
     * @param {String} opts.configldapMemberOfMappingRealMemberOfValueFormat 
     * @param {String} opts.configldapMemberOfMappingPydioMemberOfAttribute 
     * @param {String} opts.configldapMemberOfMappingPydioMemberOfValueFormat 
     * @param {String} opts.configldapRolePrefix 
     * @param {String} opts.configldapSchedule 
     * @param {String} opts.configldapSchedulerDetails 
     * @param {Boolean} opts.configldapSyncOnly 
     * @param {String} opts.configoauthBaseURL 
     * @param {String} opts.configoauthAuthorizeURL 
     * @param {String} opts.configoauthTokenURL 
     * @param {String} opts.configoauthUserInfoURL 
     * @param {String} opts.configoauthClientID 
     * @param {String} opts.configoauthClientSecret 
     * @param {String} opts.configoauthRedirectURI 
     * @param {Array.<String>} opts.configoauthGroups 
     * @param {Boolean} opts.configoauthUseLoginAsID 
     * @param {Boolean} opts.configoauthUseBrokenAuthHeaderProvider 
     * @param {String} opts.configmockJsonIdentity 
     * @param {Array.<String>} opts.sites 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntOAuth2ConnectorResponse} and HTTP response
     */
    deleteOAuth2ConnectorWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteOAuth2Connector");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'type': opts['type'],
        'name': opts['name'],
        'configoidc.issuer': opts['configoidcIssuer'],
        'configoidc.clientID': opts['configoidcClientID'],
        'configoidc.clientSecret': opts['configoidcClientSecret'],
        'configoidc.redirectURI': opts['configoidcRedirectURI'],
        'configoidc.basicAuthUnsupported': opts['configoidcBasicAuthUnsupported'],
        'configoidc.hostedDomains': this.apiClient.buildCollectionParam(opts['configoidcHostedDomains'], 'multi'),
        'configoidc.scopes': this.apiClient.buildCollectionParam(opts['configoidcScopes'], 'multi'),
        'configoidc.insecureSkipEmailVerified': opts['configoidcInsecureSkipEmailVerified'],
        'configoidc.getUserInfo': opts['configoidcGetUserInfo'],
        'configoidc.userIDKey': opts['configoidcUserIDKey'],
        'configoidc.userNameKey': opts['configoidcUserNameKey'],
        'configsaml.ssoURL': opts['configsamlSsoURL'],
        'configsaml.ca': opts['configsamlCa'],
        'configsaml.redirectURI': opts['configsamlRedirectURI'],
        'configsaml.usernameAttr': opts['configsamlUsernameAttr'],
        'configsaml.emailAttr': opts['configsamlEmailAttr'],
        'configsaml.groupsAttr': opts['configsamlGroupsAttr'],
        'configsaml.caData': opts['configsamlCaData'],
        'configsaml.insecureSkipSignatureValidation': opts['configsamlInsecureSkipSignatureValidation'],
        'configsaml.entityIssuer': opts['configsamlEntityIssuer'],
        'configsaml.ssoIssuer': opts['configsamlSsoIssuer'],
        'configsaml.groupsDelim': opts['configsamlGroupsDelim'],
        'configsaml.nameIDPolicyFormat': opts['configsamlNameIDPolicyFormat'],
        'configbitbucket.clientID': opts['configbitbucketClientID'],
        'configbitbucket.clientSecret': opts['configbitbucketClientSecret'],
        'configbitbucket.redirectURI': opts['configbitbucketRedirectURI'],
        'configbitbucket.teams': this.apiClient.buildCollectionParam(opts['configbitbucketTeams'], 'multi'),
        'configgithub.clientID': opts['configgithubClientID'],
        'configgithub.clientSecret': opts['configgithubClientSecret'],
        'configgithub.redirectURI': opts['configgithubRedirectURI'],
        'configgithub.loadAllGroups': opts['configgithubLoadAllGroups'],
        'configgithub.teamNameField': opts['configgithubTeamNameField'],
        'configgithub.useLoginAsID': opts['configgithubUseLoginAsID'],
        'configgithub.hostName': opts['configgithubHostName'],
        'configgithub.rootCA': opts['configgithubRootCA'],
        'configgitlab.baseURL': opts['configgitlabBaseURL'],
        'configgitlab.clientID': opts['configgitlabClientID'],
        'configgitlab.clientSecret': opts['configgitlabClientSecret'],
        'configgitlab.redirectURI': opts['configgitlabRedirectURI'],
        'configgitlab.groups': this.apiClient.buildCollectionParam(opts['configgitlabGroups'], 'multi'),
        'configgitlab.userLoginAsID': opts['configgitlabUserLoginAsID'],
        'configlinkedin.clientID': opts['configlinkedinClientID'],
        'configlinkedin.clientSecret': opts['configlinkedinClientSecret'],
        'configlinkedin.redirectURI': opts['configlinkedinRedirectURI'],
        'configmicrosoft.clientID': opts['configmicrosoftClientID'],
        'configmicrosoft.clientSecret': opts['configmicrosoftClientSecret'],
        'configmicrosoft.redirectURI': opts['configmicrosoftRedirectURI'],
        'configmicrosoft.tenant': opts['configmicrosoftTenant'],
        'configmicrosoft.groups': this.apiClient.buildCollectionParam(opts['configmicrosoftGroups'], 'multi'),
        'configmicrosoft.onlySecurityGroups': opts['configmicrosoftOnlySecurityGroups'],
        'configmicrosoft.groupNameFormat': opts['configmicrosoftGroupNameFormat'],
        'configmicrosoft.useGroupsAsWhitelist': opts['configmicrosoftUseGroupsAsWhitelist'],
        'configldap.ConfigId': opts['configldapConfigId'],
        'configldap.DomainName': opts['configldapDomainName'],
        'configldap.Host': opts['configldapHost'],
        'configldap.Connection': opts['configldapConnection'],
        'configldap.BindDN': opts['configldapBindDN'],
        'configldap.BindPW': opts['configldapBindPW'],
        'configldap.BindAnonymous': opts['configldapBindAnonymous'],
        'configldap.SkipVerifyCertificate': opts['configldapSkipVerifyCertificate'],
        'configldap.RootCA': opts['configldapRootCA'],
        'configldap.RootCAData': opts['configldapRootCAData'],
        'configldap.PageSize': opts['configldapPageSize'],
        'configldap.User.DNs': this.apiClient.buildCollectionParam(opts['configldapUserDNs'], 'multi'),
        'configldap.User.Filter': opts['configldapUserFilter'],
        'configldap.User.IDAttribute': opts['configldapUserIDAttribute'],
        'configldap.User.DisplayAttribute': opts['configldapUserDisplayAttribute'],
        'configldap.User.Scope': opts['configldapUserScope'],
        'configldap.MemberOfMapping.Mapping.LeftAttribute': opts['configldapMemberOfMappingMappingLeftAttribute'],
        'configldap.MemberOfMapping.Mapping.RightAttribute': opts['configldapMemberOfMappingMappingRightAttribute'],
        'configldap.MemberOfMapping.Mapping.RuleString': opts['configldapMemberOfMappingMappingRuleString'],
        'configldap.MemberOfMapping.Mapping.RolePrefix': opts['configldapMemberOfMappingMappingRolePrefix'],
        'configldap.MemberOfMapping.GroupFilter.DNs': this.apiClient.buildCollectionParam(opts['configldapMemberOfMappingGroupFilterDNs'], 'multi'),
        'configldap.MemberOfMapping.GroupFilter.Filter': opts['configldapMemberOfMappingGroupFilterFilter'],
        'configldap.MemberOfMapping.GroupFilter.IDAttribute': opts['configldapMemberOfMappingGroupFilterIDAttribute'],
        'configldap.MemberOfMapping.GroupFilter.DisplayAttribute': opts['configldapMemberOfMappingGroupFilterDisplayAttribute'],
        'configldap.MemberOfMapping.GroupFilter.Scope': opts['configldapMemberOfMappingGroupFilterScope'],
        'configldap.MemberOfMapping.SupportNestedGroup': opts['configldapMemberOfMappingSupportNestedGroup'],
        'configldap.MemberOfMapping.RealMemberOf': opts['configldapMemberOfMappingRealMemberOf'],
        'configldap.MemberOfMapping.RealMemberOfAttribute': opts['configldapMemberOfMappingRealMemberOfAttribute'],
        'configldap.MemberOfMapping.RealMemberOfValueFormat': opts['configldapMemberOfMappingRealMemberOfValueFormat'],
        'configldap.MemberOfMapping.PydioMemberOfAttribute': opts['configldapMemberOfMappingPydioMemberOfAttribute'],
        'configldap.MemberOfMapping.PydioMemberOfValueFormat': opts['configldapMemberOfMappingPydioMemberOfValueFormat'],
        'configldap.RolePrefix': opts['configldapRolePrefix'],
        'configldap.Schedule': opts['configldapSchedule'],
        'configldap.SchedulerDetails': opts['configldapSchedulerDetails'],
        'configldap.SyncOnly': opts['configldapSyncOnly'],
        'configoauth.baseURL': opts['configoauthBaseURL'],
        'configoauth.authorizeURL': opts['configoauthAuthorizeURL'],
        'configoauth.tokenURL': opts['configoauthTokenURL'],
        'configoauth.userInfoURL': opts['configoauthUserInfoURL'],
        'configoauth.clientID': opts['configoauthClientID'],
        'configoauth.clientSecret': opts['configoauthClientSecret'],
        'configoauth.redirectURI': opts['configoauthRedirectURI'],
        'configoauth.groups': this.apiClient.buildCollectionParam(opts['configoauthGroups'], 'multi'),
        'configoauth.useLoginAsID': opts['configoauthUseLoginAsID'],
        'configoauth.useBrokenAuthHeaderProvider': opts['configoauthUseBrokenAuthHeaderProvider'],
        'configmock.jsonIdentity': opts['configmockJsonIdentity'],
        'sites': this.apiClient.buildCollectionParam(opts['sites'], 'multi')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EntOAuth2ConnectorResponse;
      return this.apiClient.callApi(
        '/config/oauth2connectors/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] Delete an oauth2 client
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {String} opts.type 
     * @param {String} opts.name 
     * @param {String} opts.configoidcIssuer 
     * @param {String} opts.configoidcClientID 
     * @param {String} opts.configoidcClientSecret 
     * @param {String} opts.configoidcRedirectURI 
     * @param {Boolean} opts.configoidcBasicAuthUnsupported 
     * @param {Array.<String>} opts.configoidcHostedDomains 
     * @param {Array.<String>} opts.configoidcScopes 
     * @param {Boolean} opts.configoidcInsecureSkipEmailVerified 
     * @param {Boolean} opts.configoidcGetUserInfo 
     * @param {String} opts.configoidcUserIDKey 
     * @param {String} opts.configoidcUserNameKey 
     * @param {String} opts.configsamlSsoURL 
     * @param {String} opts.configsamlCa 
     * @param {String} opts.configsamlRedirectURI 
     * @param {String} opts.configsamlUsernameAttr 
     * @param {String} opts.configsamlEmailAttr 
     * @param {String} opts.configsamlGroupsAttr 
     * @param {String} opts.configsamlCaData 
     * @param {Boolean} opts.configsamlInsecureSkipSignatureValidation 
     * @param {String} opts.configsamlEntityIssuer 
     * @param {String} opts.configsamlSsoIssuer 
     * @param {String} opts.configsamlGroupsDelim 
     * @param {String} opts.configsamlNameIDPolicyFormat 
     * @param {String} opts.configbitbucketClientID 
     * @param {String} opts.configbitbucketClientSecret 
     * @param {String} opts.configbitbucketRedirectURI 
     * @param {Array.<String>} opts.configbitbucketTeams 
     * @param {String} opts.configgithubClientID 
     * @param {String} opts.configgithubClientSecret 
     * @param {String} opts.configgithubRedirectURI 
     * @param {Boolean} opts.configgithubLoadAllGroups 
     * @param {String} opts.configgithubTeamNameField 
     * @param {Boolean} opts.configgithubUseLoginAsID 
     * @param {String} opts.configgithubHostName For GitHub enterprise
     * @param {String} opts.configgithubRootCA 
     * @param {String} opts.configgitlabBaseURL 
     * @param {String} opts.configgitlabClientID 
     * @param {String} opts.configgitlabClientSecret 
     * @param {String} opts.configgitlabRedirectURI 
     * @param {Array.<String>} opts.configgitlabGroups 
     * @param {Boolean} opts.configgitlabUserLoginAsID 
     * @param {String} opts.configlinkedinClientID 
     * @param {String} opts.configlinkedinClientSecret 
     * @param {String} opts.configlinkedinRedirectURI 
     * @param {String} opts.configmicrosoftClientID 
     * @param {String} opts.configmicrosoftClientSecret 
     * @param {String} opts.configmicrosoftRedirectURI 
     * @param {String} opts.configmicrosoftTenant 
     * @param {Array.<String>} opts.configmicrosoftGroups 
     * @param {Boolean} opts.configmicrosoftOnlySecurityGroups 
     * @param {String} opts.configmicrosoftGroupNameFormat 
     * @param {Boolean} opts.configmicrosoftUseGroupsAsWhitelist 
     * @param {String} opts.configldapConfigId 
     * @param {String} opts.configldapDomainName 
     * @param {String} opts.configldapHost 
     * @param {String} opts.configldapConnection 
     * @param {String} opts.configldapBindDN 
     * @param {String} opts.configldapBindPW 
     * @param {Boolean} opts.configldapBindAnonymous 
     * @param {Boolean} opts.configldapSkipVerifyCertificate 
     * @param {String} opts.configldapRootCA 
     * @param {String} opts.configldapRootCAData To be converted to []byte
     * @param {Number} opts.configldapPageSize 
     * @param {Array.<String>} opts.configldapUserDNs 
     * @param {String} opts.configldapUserFilter 
     * @param {String} opts.configldapUserIDAttribute 
     * @param {String} opts.configldapUserDisplayAttribute 
     * @param {String} opts.configldapUserScope 
     * @param {String} opts.configldapMemberOfMappingMappingLeftAttribute 
     * @param {String} opts.configldapMemberOfMappingMappingRightAttribute 
     * @param {String} opts.configldapMemberOfMappingMappingRuleString 
     * @param {String} opts.configldapMemberOfMappingMappingRolePrefix 
     * @param {Array.<String>} opts.configldapMemberOfMappingGroupFilterDNs 
     * @param {String} opts.configldapMemberOfMappingGroupFilterFilter 
     * @param {String} opts.configldapMemberOfMappingGroupFilterIDAttribute 
     * @param {String} opts.configldapMemberOfMappingGroupFilterDisplayAttribute 
     * @param {String} opts.configldapMemberOfMappingGroupFilterScope 
     * @param {Boolean} opts.configldapMemberOfMappingSupportNestedGroup 
     * @param {Boolean} opts.configldapMemberOfMappingRealMemberOf 
     * @param {String} opts.configldapMemberOfMappingRealMemberOfAttribute 
     * @param {String} opts.configldapMemberOfMappingRealMemberOfValueFormat 
     * @param {String} opts.configldapMemberOfMappingPydioMemberOfAttribute 
     * @param {String} opts.configldapMemberOfMappingPydioMemberOfValueFormat 
     * @param {String} opts.configldapRolePrefix 
     * @param {String} opts.configldapSchedule 
     * @param {String} opts.configldapSchedulerDetails 
     * @param {Boolean} opts.configldapSyncOnly 
     * @param {String} opts.configoauthBaseURL 
     * @param {String} opts.configoauthAuthorizeURL 
     * @param {String} opts.configoauthTokenURL 
     * @param {String} opts.configoauthUserInfoURL 
     * @param {String} opts.configoauthClientID 
     * @param {String} opts.configoauthClientSecret 
     * @param {String} opts.configoauthRedirectURI 
     * @param {Array.<String>} opts.configoauthGroups 
     * @param {Boolean} opts.configoauthUseLoginAsID 
     * @param {Boolean} opts.configoauthUseBrokenAuthHeaderProvider 
     * @param {String} opts.configmockJsonIdentity 
     * @param {Array.<String>} opts.sites 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntOAuth2ConnectorResponse}
     */
    deleteOAuth2Connector(id, opts) {
      return this.deleteOAuth2ConnectorWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] Delete a versioning policy
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} opts.name 
     * @param {String} opts.description 
     * @param {String} opts.versionsDataSourceName 
     * @param {String} opts.versionsDataSourceBucket 
     * @param {String} opts.maxTotalSize 
     * @param {String} opts.maxSizePerFile 
     * @param {String} opts.ignoreFilesGreaterThan 
     * @param {module:model/String} opts.nodeDeletedStrategy  (default to 'KeepAll')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntDeleteVersioningPolicyResponse} and HTTP response
     */
    deleteVersioningPolicyWithHttpInfo(uuid, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling deleteVersioningPolicy");
      }

      let pathParams = {
        'Uuid': uuid
      };
      let queryParams = {
        'Name': opts['name'],
        'Description': opts['description'],
        'VersionsDataSourceName': opts['versionsDataSourceName'],
        'VersionsDataSourceBucket': opts['versionsDataSourceBucket'],
        'MaxTotalSize': opts['maxTotalSize'],
        'MaxSizePerFile': opts['maxSizePerFile'],
        'IgnoreFilesGreaterThan': opts['ignoreFilesGreaterThan'],
        'NodeDeletedStrategy': opts['nodeDeletedStrategy']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EntDeleteVersioningPolicyResponse;
      return this.apiClient.callApi(
        '/config/versioning/{Uuid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] Delete a versioning policy
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} opts.name 
     * @param {String} opts.description 
     * @param {String} opts.versionsDataSourceName 
     * @param {String} opts.versionsDataSourceBucket 
     * @param {String} opts.maxTotalSize 
     * @param {String} opts.maxSizePerFile 
     * @param {String} opts.ignoreFilesGreaterThan 
     * @param {module:model/String} opts.nodeDeletedStrategy  (default to 'KeepAll')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntDeleteVersioningPolicyResponse}
     */
    deleteVersioningPolicy(uuid, opts) {
      return this.deleteVersioningPolicyWithHttpInfo(uuid, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] Delete a virtual node
     * @param {String} uuid ------------------------------------ Core identification of the node ------------------------------------
     * @param {Object} opts Optional parameters
     * @param {String} opts.path 
     * @param {module:model/String} opts.type  (default to 'UNKNOWN')
     * @param {String} opts.size Size of the file, or cumulated size of folder
     * @param {String} opts.mTime Last modification Timestamp
     * @param {Number} opts.mode Permission mode, like 0777
     * @param {String} opts.etag Hash of the content if node is a LEAF, Uuid or
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntDeleteVirtualNodeResponse} and HTTP response
     */
    deleteVirtualNodeWithHttpInfo(uuid, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling deleteVirtualNode");
      }

      let pathParams = {
        'Uuid': uuid
      };
      let queryParams = {
        'Path': opts['path'],
        'Type': opts['type'],
        'Size': opts['size'],
        'MTime': opts['mTime'],
        'Mode': opts['mode'],
        'Etag': opts['etag']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EntDeleteVirtualNodeResponse;
      return this.apiClient.callApi(
        '/config/virtualnodes/{Uuid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] Delete a virtual node
     * @param {String} uuid ------------------------------------ Core identification of the node ------------------------------------
     * @param {Object} opts Optional parameters
     * @param {String} opts.path 
     * @param {module:model/String} opts.type  (default to 'UNKNOWN')
     * @param {String} opts.size Size of the file, or cumulated size of folder
     * @param {String} opts.mTime Last modification Timestamp
     * @param {Number} opts.mode Permission mode, like 0777
     * @param {String} opts.etag Hash of the content if node is a LEAF, Uuid or
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntDeleteVirtualNodeResponse}
     */
    deleteVirtualNode(uuid, opts) {
      return this.deleteVirtualNodeWithHttpInfo(uuid, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] List additional user directories
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntExternalDirectoryCollection} and HTTP response
     */
    listExternalDirectoriesWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EntExternalDirectoryCollection;
      return this.apiClient.callApi(
        '/config/directories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] List additional user directories
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntExternalDirectoryCollection}
     */
    listExternalDirectories() {
      return this.listExternalDirectoriesWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] List oauth2 clients
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntOAuth2ClientCollection} and HTTP response
     */
    listOAuth2ClientsWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EntOAuth2ClientCollection;
      return this.apiClient.callApi(
        '/config/oauth2clients', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] List oauth2 clients
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntOAuth2ClientCollection}
     */
    listOAuth2Clients() {
      return this.listOAuth2ClientsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] List oauth2 connectors
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntOAuth2ConnectorCollection} and HTTP response
     */
    listOAuth2ConnectorsWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EntOAuth2ConnectorCollection;
      return this.apiClient.callApi(
        '/config/oauth2connectors', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] List oauth2 connectors
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntOAuth2ConnectorCollection}
     */
    listOAuth2Connectors() {
      return this.listOAuth2ConnectorsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] List configured sites
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntListSitesResponse} and HTTP response
     */
    listSitesWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EntListSitesResponse;
      return this.apiClient.callApi(
        '/config/sites', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] List configured sites
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntListSitesResponse}
     */
    listSites() {
      return this.listSitesWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] Sends an arbitrary config and try to ping the server and bind
     * @param {module:model/EntExternalDirectoryPingRequest} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntExternalDirectoryTestResponse} and HTTP response
     */
    pingExternalDirectoryWithHttpInfo(body) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling pingExternalDirectory");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EntExternalDirectoryTestResponse;
      return this.apiClient.callApi(
        '/config/directories-test/ping', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] Sends an arbitrary config and try to ping the server and bind
     * @param {module:model/EntExternalDirectoryPingRequest} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntExternalDirectoryTestResponse}
     */
    pingExternalDirectory(body) {
      return this.pingExternalDirectoryWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] Add/Create an external directory
     * @param {String} configId Id of the external directory
     * @param {module:model/EntExternalDirectoryConfig} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntExternalDirectoryResponse} and HTTP response
     */
    putExternalDirectoryWithHttpInfo(configId, body) {
      let postBody = body;
      // verify the required parameter 'configId' is set
      if (configId === undefined || configId === null) {
        throw new Error("Missing the required parameter 'configId' when calling putExternalDirectory");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling putExternalDirectory");
      }

      let pathParams = {
        'ConfigId': configId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EntExternalDirectoryResponse;
      return this.apiClient.callApi(
        '/config/directories/{ConfigId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] Add/Create an external directory
     * @param {String} configId Id of the external directory
     * @param {module:model/EntExternalDirectoryConfig} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntExternalDirectoryResponse}
     */
    putExternalDirectory(configId, body) {
      return this.putExternalDirectoryWithHttpInfo(configId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] Add/Create a new oauth2 client
     * @param {String} clientId 
     * @param {module:model/InlineObject} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntOAuth2ClientResponse} and HTTP response
     */
    putOAuth2ClientWithHttpInfo(clientId, body) {
      let postBody = body;
      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling putOAuth2Client");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling putOAuth2Client");
      }

      let pathParams = {
        'client_id': clientId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EntOAuth2ClientResponse;
      return this.apiClient.callApi(
        '/config/oauth2clients/{client_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] Add/Create a new oauth2 client
     * @param {String} clientId 
     * @param {module:model/InlineObject} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntOAuth2ClientResponse}
     */
    putOAuth2Client(clientId, body) {
      return this.putOAuth2ClientWithHttpInfo(clientId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] Add/Create a new oauth2 client
     * @param {String} id 
     * @param {module:model/InlineObject1} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntOAuth2ConnectorResponse} and HTTP response
     */
    putOAuth2ConnectorWithHttpInfo(id, body) {
      let postBody = body;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling putOAuth2Connector");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling putOAuth2Connector");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EntOAuth2ConnectorResponse;
      return this.apiClient.callApi(
        '/config/oauth2connectors/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] Add/Create a new oauth2 client
     * @param {String} id 
     * @param {module:model/InlineObject1} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntOAuth2ConnectorResponse}
     */
    putOAuth2Connector(id, body) {
      return this.putOAuth2ConnectorWithHttpInfo(id, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] Add/Create a new oauth2 client
     * @param {module:model/AuthOAuth2ConnectorCollection} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntOAuth2ConnectorResponse} and HTTP response
     */
    putOAuth2ConnectorsWithHttpInfo(body) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling putOAuth2Connectors");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EntOAuth2ConnectorResponse;
      return this.apiClient.callApi(
        '/config/oauth2connectors', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] Add/Create a new oauth2 client
     * @param {module:model/AuthOAuth2ConnectorCollection} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntOAuth2ConnectorResponse}
     */
    putOAuth2Connectors(body) {
      return this.putOAuth2ConnectorsWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] Create or update a versioning policy
     * @param {String} uuid 
     * @param {module:model/InlineObject2} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TreeVersioningPolicy} and HTTP response
     */
    putVersioningPolicyWithHttpInfo(uuid, body) {
      let postBody = body;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling putVersioningPolicy");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling putVersioningPolicy");
      }

      let pathParams = {
        'Uuid': uuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TreeVersioningPolicy;
      return this.apiClient.callApi(
        '/config/versioning/{Uuid}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] Create or update a versioning policy
     * @param {String} uuid 
     * @param {module:model/InlineObject2} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TreeVersioningPolicy}
     */
    putVersioningPolicy(uuid, body) {
      return this.putVersioningPolicyWithHttpInfo(uuid, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] Create or update a virtual node
     * @param {String} uuid ------------------------------------ Core identification of the node ------------------------------------
     * @param {module:model/InlineObject3} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TreeNode} and HTTP response
     */
    putVirtualNodeWithHttpInfo(uuid, body) {
      let postBody = body;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling putVirtualNode");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling putVirtualNode");
      }

      let pathParams = {
        'Uuid': uuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TreeNode;
      return this.apiClient.callApi(
        '/config/virtualnodes/{Uuid}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] Create or update a virtual node
     * @param {String} uuid ------------------------------------ Core identification of the node ------------------------------------
     * @param {module:model/InlineObject3} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TreeNode}
     */
    putVirtualNode(uuid, body) {
      return this.putVirtualNodeWithHttpInfo(uuid, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * [Enterprise Only] Sends an arbitrary config and try to ldapsearch using a given SearchFilter
     * @param {module:model/EntExternalDirectorySearchRequest} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntExternalDirectoryTestResponse} and HTTP response
     */
    searchExternalDirectoryWithHttpInfo(body) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling searchExternalDirectory");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EntExternalDirectoryTestResponse;
      return this.apiClient.callApi(
        '/config/directories-test/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * [Enterprise Only] Sends an arbitrary config and try to ldapsearch using a given SearchFilter
     * @param {module:model/EntExternalDirectorySearchRequest} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EntExternalDirectoryTestResponse}
     */
    searchExternalDirectory(body) {
      return this.searchExternalDirectoryWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
