/**
 * Pydio Cells Enterprise Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ActivityObject from './model/ActivityObject';
import ActivityObjectType from './model/ActivityObjectType';
import AuthLdapMapping from './model/AuthLdapMapping';
import AuthLdapMemberOfMapping from './model/AuthLdapMemberOfMapping';
import AuthLdapSearchFilter from './model/AuthLdapSearchFilter';
import AuthLdapServerConfig from './model/AuthLdapServerConfig';
import AuthOAuth2ClientConfig from './model/AuthOAuth2ClientConfig';
import AuthOAuth2ConnectorBitbucketConfig from './model/AuthOAuth2ConnectorBitbucketConfig';
import AuthOAuth2ConnectorCollection from './model/AuthOAuth2ConnectorCollection';
import AuthOAuth2ConnectorConfig from './model/AuthOAuth2ConnectorConfig';
import AuthOAuth2ConnectorGithubConfig from './model/AuthOAuth2ConnectorGithubConfig';
import AuthOAuth2ConnectorGithubConfigOrg from './model/AuthOAuth2ConnectorGithubConfigOrg';
import AuthOAuth2ConnectorGitlabConfig from './model/AuthOAuth2ConnectorGitlabConfig';
import AuthOAuth2ConnectorLinkedinConfig from './model/AuthOAuth2ConnectorLinkedinConfig';
import AuthOAuth2ConnectorMicrosoftConfig from './model/AuthOAuth2ConnectorMicrosoftConfig';
import AuthOAuth2ConnectorOAuthConfig from './model/AuthOAuth2ConnectorOAuthConfig';
import AuthOAuth2ConnectorOIDCConfig from './model/AuthOAuth2ConnectorOIDCConfig';
import AuthOAuth2ConnectorPydioConfig from './model/AuthOAuth2ConnectorPydioConfig';
import AuthOAuth2ConnectorPydioConfigConnector from './model/AuthOAuth2ConnectorPydioConfigConnector';
import AuthOAuth2ConnectorSAMLConfig from './model/AuthOAuth2ConnectorSAMLConfig';
import AuthOAuth2MappingRule from './model/AuthOAuth2MappingRule';
import AuthPatListResponse from './model/AuthPatListResponse';
import AuthPatType from './model/AuthPatType';
import AuthPersonalAccessToken from './model/AuthPersonalAccessToken';
import CertLicenseInfo from './model/CertLicenseInfo';
import CertLicenseStatsResponse from './model/CertLicenseStatsResponse';
import CertPutLicenseInfoRequest from './model/CertPutLicenseInfoRequest';
import CertPutLicenseInfoResponse from './model/CertPutLicenseInfoResponse';
import EntActionTemplate from './model/EntActionTemplate';
import EntConnector from './model/EntConnector';
import EntDeleteActionTemplateResponse from './model/EntDeleteActionTemplateResponse';
import EntDeleteJobTemplateResponse from './model/EntDeleteJobTemplateResponse';
import EntDeleteSelectorTemplateResponse from './model/EntDeleteSelectorTemplateResponse';
import EntDeleteVersioningPolicyResponse from './model/EntDeleteVersioningPolicyResponse';
import EntDeleteVirtualNodeResponse from './model/EntDeleteVirtualNodeResponse';
import EntDocTemplatePiece from './model/EntDocTemplatePiece';
import EntDocTemplatesResponse from './model/EntDocTemplatesResponse';
import EntExternalDirectoryCollection from './model/EntExternalDirectoryCollection';
import EntExternalDirectoryConfig from './model/EntExternalDirectoryConfig';
import EntExternalDirectoryResponse from './model/EntExternalDirectoryResponse';
import EntFrontLoginConnectorsResponse from './model/EntFrontLoginConnectorsResponse';
import EntListAccessTokensRequest from './model/EntListAccessTokensRequest';
import EntListActionTemplatesRequest from './model/EntListActionTemplatesRequest';
import EntListActionTemplatesResponse from './model/EntListActionTemplatesResponse';
import EntListJobTemplatesRequest from './model/EntListJobTemplatesRequest';
import EntListJobTemplatesResponse from './model/EntListJobTemplatesResponse';
import EntListSelectorTemplatesRequest from './model/EntListSelectorTemplatesRequest';
import EntListSelectorTemplatesResponse from './model/EntListSelectorTemplatesResponse';
import EntListSitesResponse from './model/EntListSitesResponse';
import EntOAuth2ClientCollection from './model/EntOAuth2ClientCollection';
import EntOAuth2ClientResponse from './model/EntOAuth2ClientResponse';
import EntOAuth2ConnectorCollection from './model/EntOAuth2ConnectorCollection';
import EntOAuth2ConnectorResponse from './model/EntOAuth2ConnectorResponse';
import EntPersonalAccessTokenRequest from './model/EntPersonalAccessTokenRequest';
import EntPersonalAccessTokenResponse from './model/EntPersonalAccessTokenResponse';
import EntPlaygroundRequest from './model/EntPlaygroundRequest';
import EntPlaygroundResponse from './model/EntPlaygroundResponse';
import EntPutActionTemplateRequest from './model/EntPutActionTemplateRequest';
import EntPutActionTemplateResponse from './model/EntPutActionTemplateResponse';
import EntPutJobTemplateRequest from './model/EntPutJobTemplateRequest';
import EntPutJobTemplateResponse from './model/EntPutJobTemplateResponse';
import EntPutSelectorTemplateRequest from './model/EntPutSelectorTemplateRequest';
import EntPutSelectorTemplateResponse from './model/EntPutSelectorTemplateResponse';
import EntSelectorTemplate from './model/EntSelectorTemplate';
import IdmACL from './model/IdmACL';
import IdmACLAction from './model/IdmACLAction';
import IdmPolicy from './model/IdmPolicy';
import IdmPolicyCondition from './model/IdmPolicyCondition';
import IdmPolicyEffect from './model/IdmPolicyEffect';
import IdmPolicyGroup from './model/IdmPolicyGroup';
import IdmPolicyResourceGroup from './model/IdmPolicyResourceGroup';
import IdmRole from './model/IdmRole';
import IdmUser from './model/IdmUser';
import IdmWorkspace from './model/IdmWorkspace';
import IdmWorkspaceScope from './model/IdmWorkspaceScope';
import InstallProxyConfig from './model/InstallProxyConfig';
import InstallTLSCertificate from './model/InstallTLSCertificate';
import InstallTLSLetsEncrypt from './model/InstallTLSLetsEncrypt';
import InstallTLSSelfSigned from './model/InstallTLSSelfSigned';
import IpbanBannedConnection from './model/IpbanBannedConnection';
import IpbanConnectionAttempt from './model/IpbanConnectionAttempt';
import IpbanIPsCollection from './model/IpbanIPsCollection';
import IpbanListBansCollection from './model/IpbanListBansCollection';
import IpbanUnbanRequest from './model/IpbanUnbanRequest';
import IpbanUnbanResponse from './model/IpbanUnbanResponse';
import JobsAction from './model/JobsAction';
import JobsActionLog from './model/JobsActionLog';
import JobsActionMessage from './model/JobsActionMessage';
import JobsActionOutput from './model/JobsActionOutput';
import JobsActionOutputFilter from './model/JobsActionOutputFilter';
import JobsContextMetaFilter from './model/JobsContextMetaFilter';
import JobsContextMetaFilterType from './model/JobsContextMetaFilterType';
import JobsDataSourceSelector from './model/JobsDataSourceSelector';
import JobsDataSourceSelectorType from './model/JobsDataSourceSelectorType';
import JobsDeleteJobResponse from './model/JobsDeleteJobResponse';
import JobsIdmSelector from './model/JobsIdmSelector';
import JobsIdmSelectorType from './model/JobsIdmSelectorType';
import JobsJob from './model/JobsJob';
import JobsJobParameter from './model/JobsJobParameter';
import JobsNodesSelector from './model/JobsNodesSelector';
import JobsPutJobRequest from './model/JobsPutJobRequest';
import JobsPutJobResponse from './model/JobsPutJobResponse';
import JobsSchedule from './model/JobsSchedule';
import JobsTask from './model/JobsTask';
import JobsTaskStatus from './model/JobsTaskStatus';
import JobsTriggerFilter from './model/JobsTriggerFilter';
import JobsUsersSelector from './model/JobsUsersSelector';
import ListLogRequestLogFormat from './model/ListLogRequestLogFormat';
import LogListLogRequest from './model/LogListLogRequest';
import LogLogMessage from './model/LogLogMessage';
import LogRelType from './model/LogRelType';
import LogTimeRangeCursor from './model/LogTimeRangeCursor';
import LogTimeRangeRequest from './model/LogTimeRangeRequest';
import LogTimeRangeResult from './model/LogTimeRangeResult';
import NodeChangeEventEventType from './model/NodeChangeEventEventType';
import ObjectDataSource from './model/ObjectDataSource';
import ObjectEncryptionMode from './model/ObjectEncryptionMode';
import ObjectStorageType from './model/ObjectStorageType';
import ProtobufAny from './model/ProtobufAny';
import ReportsAuditedWorkspace from './model/ReportsAuditedWorkspace';
import ReportsSharedResource from './model/ReportsSharedResource';
import ReportsSharedResourceShareType from './model/ReportsSharedResourceShareType';
import ReportsSharedResourcesRequest from './model/ReportsSharedResourcesRequest';
import ReportsSharedResourcesResponse from './model/ReportsSharedResourcesResponse';
import RestDeleteResponse from './model/RestDeleteResponse';
import RestError from './model/RestError';
import RestLogMessageCollection from './model/RestLogMessageCollection';
import RestRevokeResponse from './model/RestRevokeResponse';
import RestTimeRangeResultCollection from './model/RestTimeRangeResultCollection';
import ServiceOperationType from './model/ServiceOperationType';
import ServiceQuery from './model/ServiceQuery';
import ServiceResourcePolicy from './model/ServiceResourcePolicy';
import ServiceResourcePolicyAction from './model/ServiceResourcePolicyAction';
import ServiceResourcePolicyPolicyEffect from './model/ServiceResourcePolicyPolicyEffect';
import ServiceResourcePolicyQuery from './model/ServiceResourcePolicyQuery';
import TreeChangeLog from './model/TreeChangeLog';
import TreeNode from './model/TreeNode';
import TreeNodeChangeEvent from './model/TreeNodeChangeEvent';
import TreeNodeType from './model/TreeNodeType';
import TreeVersioningKeepPeriod from './model/TreeVersioningKeepPeriod';
import TreeVersioningNodeDeletedStrategy from './model/TreeVersioningNodeDeletedStrategy';
import TreeVersioningPolicy from './model/TreeVersioningPolicy';
import TreeWorkspaceRelativePath from './model/TreeWorkspaceRelativePath';
import AuditDataServiceApi from './api/AuditDataServiceApi';
import EnterpriseConfigServiceApi from './api/EnterpriseConfigServiceApi';
import EnterpriseFrontendServiceApi from './api/EnterpriseFrontendServiceApi';
import EnterpriseLogServiceApi from './api/EnterpriseLogServiceApi';
import EnterprisePolicyServiceApi from './api/EnterprisePolicyServiceApi';
import EnterpriseTokenServiceApi from './api/EnterpriseTokenServiceApi';
import LicenseServiceApi from './api/LicenseServiceApi';
import SchedulerServiceApi from './api/SchedulerServiceApi';


/**
* ERROR_UNKNOWN.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var PydioCellsEnterpriseRestApi = require('index'); // See note below*.
* var xxxSvc = new PydioCellsEnterpriseRestApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new PydioCellsEnterpriseRestApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new PydioCellsEnterpriseRestApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new PydioCellsEnterpriseRestApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ActivityObject model constructor.
     * @property {module:model/ActivityObject}
     */
    ActivityObject,

    /**
     * The ActivityObjectType model constructor.
     * @property {module:model/ActivityObjectType}
     */
    ActivityObjectType,

    /**
     * The AuthLdapMapping model constructor.
     * @property {module:model/AuthLdapMapping}
     */
    AuthLdapMapping,

    /**
     * The AuthLdapMemberOfMapping model constructor.
     * @property {module:model/AuthLdapMemberOfMapping}
     */
    AuthLdapMemberOfMapping,

    /**
     * The AuthLdapSearchFilter model constructor.
     * @property {module:model/AuthLdapSearchFilter}
     */
    AuthLdapSearchFilter,

    /**
     * The AuthLdapServerConfig model constructor.
     * @property {module:model/AuthLdapServerConfig}
     */
    AuthLdapServerConfig,

    /**
     * The AuthOAuth2ClientConfig model constructor.
     * @property {module:model/AuthOAuth2ClientConfig}
     */
    AuthOAuth2ClientConfig,

    /**
     * The AuthOAuth2ConnectorBitbucketConfig model constructor.
     * @property {module:model/AuthOAuth2ConnectorBitbucketConfig}
     */
    AuthOAuth2ConnectorBitbucketConfig,

    /**
     * The AuthOAuth2ConnectorCollection model constructor.
     * @property {module:model/AuthOAuth2ConnectorCollection}
     */
    AuthOAuth2ConnectorCollection,

    /**
     * The AuthOAuth2ConnectorConfig model constructor.
     * @property {module:model/AuthOAuth2ConnectorConfig}
     */
    AuthOAuth2ConnectorConfig,

    /**
     * The AuthOAuth2ConnectorGithubConfig model constructor.
     * @property {module:model/AuthOAuth2ConnectorGithubConfig}
     */
    AuthOAuth2ConnectorGithubConfig,

    /**
     * The AuthOAuth2ConnectorGithubConfigOrg model constructor.
     * @property {module:model/AuthOAuth2ConnectorGithubConfigOrg}
     */
    AuthOAuth2ConnectorGithubConfigOrg,

    /**
     * The AuthOAuth2ConnectorGitlabConfig model constructor.
     * @property {module:model/AuthOAuth2ConnectorGitlabConfig}
     */
    AuthOAuth2ConnectorGitlabConfig,

    /**
     * The AuthOAuth2ConnectorLinkedinConfig model constructor.
     * @property {module:model/AuthOAuth2ConnectorLinkedinConfig}
     */
    AuthOAuth2ConnectorLinkedinConfig,

    /**
     * The AuthOAuth2ConnectorMicrosoftConfig model constructor.
     * @property {module:model/AuthOAuth2ConnectorMicrosoftConfig}
     */
    AuthOAuth2ConnectorMicrosoftConfig,

    /**
     * The AuthOAuth2ConnectorOAuthConfig model constructor.
     * @property {module:model/AuthOAuth2ConnectorOAuthConfig}
     */
    AuthOAuth2ConnectorOAuthConfig,

    /**
     * The AuthOAuth2ConnectorOIDCConfig model constructor.
     * @property {module:model/AuthOAuth2ConnectorOIDCConfig}
     */
    AuthOAuth2ConnectorOIDCConfig,

    /**
     * The AuthOAuth2ConnectorPydioConfig model constructor.
     * @property {module:model/AuthOAuth2ConnectorPydioConfig}
     */
    AuthOAuth2ConnectorPydioConfig,

    /**
     * The AuthOAuth2ConnectorPydioConfigConnector model constructor.
     * @property {module:model/AuthOAuth2ConnectorPydioConfigConnector}
     */
    AuthOAuth2ConnectorPydioConfigConnector,

    /**
     * The AuthOAuth2ConnectorSAMLConfig model constructor.
     * @property {module:model/AuthOAuth2ConnectorSAMLConfig}
     */
    AuthOAuth2ConnectorSAMLConfig,

    /**
     * The AuthOAuth2MappingRule model constructor.
     * @property {module:model/AuthOAuth2MappingRule}
     */
    AuthOAuth2MappingRule,

    /**
     * The AuthPatListResponse model constructor.
     * @property {module:model/AuthPatListResponse}
     */
    AuthPatListResponse,

    /**
     * The AuthPatType model constructor.
     * @property {module:model/AuthPatType}
     */
    AuthPatType,

    /**
     * The AuthPersonalAccessToken model constructor.
     * @property {module:model/AuthPersonalAccessToken}
     */
    AuthPersonalAccessToken,

    /**
     * The CertLicenseInfo model constructor.
     * @property {module:model/CertLicenseInfo}
     */
    CertLicenseInfo,

    /**
     * The CertLicenseStatsResponse model constructor.
     * @property {module:model/CertLicenseStatsResponse}
     */
    CertLicenseStatsResponse,

    /**
     * The CertPutLicenseInfoRequest model constructor.
     * @property {module:model/CertPutLicenseInfoRequest}
     */
    CertPutLicenseInfoRequest,

    /**
     * The CertPutLicenseInfoResponse model constructor.
     * @property {module:model/CertPutLicenseInfoResponse}
     */
    CertPutLicenseInfoResponse,

    /**
     * The EntActionTemplate model constructor.
     * @property {module:model/EntActionTemplate}
     */
    EntActionTemplate,

    /**
     * The EntConnector model constructor.
     * @property {module:model/EntConnector}
     */
    EntConnector,

    /**
     * The EntDeleteActionTemplateResponse model constructor.
     * @property {module:model/EntDeleteActionTemplateResponse}
     */
    EntDeleteActionTemplateResponse,

    /**
     * The EntDeleteJobTemplateResponse model constructor.
     * @property {module:model/EntDeleteJobTemplateResponse}
     */
    EntDeleteJobTemplateResponse,

    /**
     * The EntDeleteSelectorTemplateResponse model constructor.
     * @property {module:model/EntDeleteSelectorTemplateResponse}
     */
    EntDeleteSelectorTemplateResponse,

    /**
     * The EntDeleteVersioningPolicyResponse model constructor.
     * @property {module:model/EntDeleteVersioningPolicyResponse}
     */
    EntDeleteVersioningPolicyResponse,

    /**
     * The EntDeleteVirtualNodeResponse model constructor.
     * @property {module:model/EntDeleteVirtualNodeResponse}
     */
    EntDeleteVirtualNodeResponse,

    /**
     * The EntDocTemplatePiece model constructor.
     * @property {module:model/EntDocTemplatePiece}
     */
    EntDocTemplatePiece,

    /**
     * The EntDocTemplatesResponse model constructor.
     * @property {module:model/EntDocTemplatesResponse}
     */
    EntDocTemplatesResponse,

    /**
     * The EntExternalDirectoryCollection model constructor.
     * @property {module:model/EntExternalDirectoryCollection}
     */
    EntExternalDirectoryCollection,

    /**
     * The EntExternalDirectoryConfig model constructor.
     * @property {module:model/EntExternalDirectoryConfig}
     */
    EntExternalDirectoryConfig,

    /**
     * The EntExternalDirectoryResponse model constructor.
     * @property {module:model/EntExternalDirectoryResponse}
     */
    EntExternalDirectoryResponse,

    /**
     * The EntFrontLoginConnectorsResponse model constructor.
     * @property {module:model/EntFrontLoginConnectorsResponse}
     */
    EntFrontLoginConnectorsResponse,

    /**
     * The EntListAccessTokensRequest model constructor.
     * @property {module:model/EntListAccessTokensRequest}
     */
    EntListAccessTokensRequest,

    /**
     * The EntListActionTemplatesRequest model constructor.
     * @property {module:model/EntListActionTemplatesRequest}
     */
    EntListActionTemplatesRequest,

    /**
     * The EntListActionTemplatesResponse model constructor.
     * @property {module:model/EntListActionTemplatesResponse}
     */
    EntListActionTemplatesResponse,

    /**
     * The EntListJobTemplatesRequest model constructor.
     * @property {module:model/EntListJobTemplatesRequest}
     */
    EntListJobTemplatesRequest,

    /**
     * The EntListJobTemplatesResponse model constructor.
     * @property {module:model/EntListJobTemplatesResponse}
     */
    EntListJobTemplatesResponse,

    /**
     * The EntListSelectorTemplatesRequest model constructor.
     * @property {module:model/EntListSelectorTemplatesRequest}
     */
    EntListSelectorTemplatesRequest,

    /**
     * The EntListSelectorTemplatesResponse model constructor.
     * @property {module:model/EntListSelectorTemplatesResponse}
     */
    EntListSelectorTemplatesResponse,

    /**
     * The EntListSitesResponse model constructor.
     * @property {module:model/EntListSitesResponse}
     */
    EntListSitesResponse,

    /**
     * The EntOAuth2ClientCollection model constructor.
     * @property {module:model/EntOAuth2ClientCollection}
     */
    EntOAuth2ClientCollection,

    /**
     * The EntOAuth2ClientResponse model constructor.
     * @property {module:model/EntOAuth2ClientResponse}
     */
    EntOAuth2ClientResponse,

    /**
     * The EntOAuth2ConnectorCollection model constructor.
     * @property {module:model/EntOAuth2ConnectorCollection}
     */
    EntOAuth2ConnectorCollection,

    /**
     * The EntOAuth2ConnectorResponse model constructor.
     * @property {module:model/EntOAuth2ConnectorResponse}
     */
    EntOAuth2ConnectorResponse,

    /**
     * The EntPersonalAccessTokenRequest model constructor.
     * @property {module:model/EntPersonalAccessTokenRequest}
     */
    EntPersonalAccessTokenRequest,

    /**
     * The EntPersonalAccessTokenResponse model constructor.
     * @property {module:model/EntPersonalAccessTokenResponse}
     */
    EntPersonalAccessTokenResponse,

    /**
     * The EntPlaygroundRequest model constructor.
     * @property {module:model/EntPlaygroundRequest}
     */
    EntPlaygroundRequest,

    /**
     * The EntPlaygroundResponse model constructor.
     * @property {module:model/EntPlaygroundResponse}
     */
    EntPlaygroundResponse,

    /**
     * The EntPutActionTemplateRequest model constructor.
     * @property {module:model/EntPutActionTemplateRequest}
     */
    EntPutActionTemplateRequest,

    /**
     * The EntPutActionTemplateResponse model constructor.
     * @property {module:model/EntPutActionTemplateResponse}
     */
    EntPutActionTemplateResponse,

    /**
     * The EntPutJobTemplateRequest model constructor.
     * @property {module:model/EntPutJobTemplateRequest}
     */
    EntPutJobTemplateRequest,

    /**
     * The EntPutJobTemplateResponse model constructor.
     * @property {module:model/EntPutJobTemplateResponse}
     */
    EntPutJobTemplateResponse,

    /**
     * The EntPutSelectorTemplateRequest model constructor.
     * @property {module:model/EntPutSelectorTemplateRequest}
     */
    EntPutSelectorTemplateRequest,

    /**
     * The EntPutSelectorTemplateResponse model constructor.
     * @property {module:model/EntPutSelectorTemplateResponse}
     */
    EntPutSelectorTemplateResponse,

    /**
     * The EntSelectorTemplate model constructor.
     * @property {module:model/EntSelectorTemplate}
     */
    EntSelectorTemplate,

    /**
     * The IdmACL model constructor.
     * @property {module:model/IdmACL}
     */
    IdmACL,

    /**
     * The IdmACLAction model constructor.
     * @property {module:model/IdmACLAction}
     */
    IdmACLAction,

    /**
     * The IdmPolicy model constructor.
     * @property {module:model/IdmPolicy}
     */
    IdmPolicy,

    /**
     * The IdmPolicyCondition model constructor.
     * @property {module:model/IdmPolicyCondition}
     */
    IdmPolicyCondition,

    /**
     * The IdmPolicyEffect model constructor.
     * @property {module:model/IdmPolicyEffect}
     */
    IdmPolicyEffect,

    /**
     * The IdmPolicyGroup model constructor.
     * @property {module:model/IdmPolicyGroup}
     */
    IdmPolicyGroup,

    /**
     * The IdmPolicyResourceGroup model constructor.
     * @property {module:model/IdmPolicyResourceGroup}
     */
    IdmPolicyResourceGroup,

    /**
     * The IdmRole model constructor.
     * @property {module:model/IdmRole}
     */
    IdmRole,

    /**
     * The IdmUser model constructor.
     * @property {module:model/IdmUser}
     */
    IdmUser,

    /**
     * The IdmWorkspace model constructor.
     * @property {module:model/IdmWorkspace}
     */
    IdmWorkspace,

    /**
     * The IdmWorkspaceScope model constructor.
     * @property {module:model/IdmWorkspaceScope}
     */
    IdmWorkspaceScope,

    /**
     * The InstallProxyConfig model constructor.
     * @property {module:model/InstallProxyConfig}
     */
    InstallProxyConfig,

    /**
     * The InstallTLSCertificate model constructor.
     * @property {module:model/InstallTLSCertificate}
     */
    InstallTLSCertificate,

    /**
     * The InstallTLSLetsEncrypt model constructor.
     * @property {module:model/InstallTLSLetsEncrypt}
     */
    InstallTLSLetsEncrypt,

    /**
     * The InstallTLSSelfSigned model constructor.
     * @property {module:model/InstallTLSSelfSigned}
     */
    InstallTLSSelfSigned,

    /**
     * The IpbanBannedConnection model constructor.
     * @property {module:model/IpbanBannedConnection}
     */
    IpbanBannedConnection,

    /**
     * The IpbanConnectionAttempt model constructor.
     * @property {module:model/IpbanConnectionAttempt}
     */
    IpbanConnectionAttempt,

    /**
     * The IpbanIPsCollection model constructor.
     * @property {module:model/IpbanIPsCollection}
     */
    IpbanIPsCollection,

    /**
     * The IpbanListBansCollection model constructor.
     * @property {module:model/IpbanListBansCollection}
     */
    IpbanListBansCollection,

    /**
     * The IpbanUnbanRequest model constructor.
     * @property {module:model/IpbanUnbanRequest}
     */
    IpbanUnbanRequest,

    /**
     * The IpbanUnbanResponse model constructor.
     * @property {module:model/IpbanUnbanResponse}
     */
    IpbanUnbanResponse,

    /**
     * The JobsAction model constructor.
     * @property {module:model/JobsAction}
     */
    JobsAction,

    /**
     * The JobsActionLog model constructor.
     * @property {module:model/JobsActionLog}
     */
    JobsActionLog,

    /**
     * The JobsActionMessage model constructor.
     * @property {module:model/JobsActionMessage}
     */
    JobsActionMessage,

    /**
     * The JobsActionOutput model constructor.
     * @property {module:model/JobsActionOutput}
     */
    JobsActionOutput,

    /**
     * The JobsActionOutputFilter model constructor.
     * @property {module:model/JobsActionOutputFilter}
     */
    JobsActionOutputFilter,

    /**
     * The JobsContextMetaFilter model constructor.
     * @property {module:model/JobsContextMetaFilter}
     */
    JobsContextMetaFilter,

    /**
     * The JobsContextMetaFilterType model constructor.
     * @property {module:model/JobsContextMetaFilterType}
     */
    JobsContextMetaFilterType,

    /**
     * The JobsDataSourceSelector model constructor.
     * @property {module:model/JobsDataSourceSelector}
     */
    JobsDataSourceSelector,

    /**
     * The JobsDataSourceSelectorType model constructor.
     * @property {module:model/JobsDataSourceSelectorType}
     */
    JobsDataSourceSelectorType,

    /**
     * The JobsDeleteJobResponse model constructor.
     * @property {module:model/JobsDeleteJobResponse}
     */
    JobsDeleteJobResponse,

    /**
     * The JobsIdmSelector model constructor.
     * @property {module:model/JobsIdmSelector}
     */
    JobsIdmSelector,

    /**
     * The JobsIdmSelectorType model constructor.
     * @property {module:model/JobsIdmSelectorType}
     */
    JobsIdmSelectorType,

    /**
     * The JobsJob model constructor.
     * @property {module:model/JobsJob}
     */
    JobsJob,

    /**
     * The JobsJobParameter model constructor.
     * @property {module:model/JobsJobParameter}
     */
    JobsJobParameter,

    /**
     * The JobsNodesSelector model constructor.
     * @property {module:model/JobsNodesSelector}
     */
    JobsNodesSelector,

    /**
     * The JobsPutJobRequest model constructor.
     * @property {module:model/JobsPutJobRequest}
     */
    JobsPutJobRequest,

    /**
     * The JobsPutJobResponse model constructor.
     * @property {module:model/JobsPutJobResponse}
     */
    JobsPutJobResponse,

    /**
     * The JobsSchedule model constructor.
     * @property {module:model/JobsSchedule}
     */
    JobsSchedule,

    /**
     * The JobsTask model constructor.
     * @property {module:model/JobsTask}
     */
    JobsTask,

    /**
     * The JobsTaskStatus model constructor.
     * @property {module:model/JobsTaskStatus}
     */
    JobsTaskStatus,

    /**
     * The JobsTriggerFilter model constructor.
     * @property {module:model/JobsTriggerFilter}
     */
    JobsTriggerFilter,

    /**
     * The JobsUsersSelector model constructor.
     * @property {module:model/JobsUsersSelector}
     */
    JobsUsersSelector,

    /**
     * The ListLogRequestLogFormat model constructor.
     * @property {module:model/ListLogRequestLogFormat}
     */
    ListLogRequestLogFormat,

    /**
     * The LogListLogRequest model constructor.
     * @property {module:model/LogListLogRequest}
     */
    LogListLogRequest,

    /**
     * The LogLogMessage model constructor.
     * @property {module:model/LogLogMessage}
     */
    LogLogMessage,

    /**
     * The LogRelType model constructor.
     * @property {module:model/LogRelType}
     */
    LogRelType,

    /**
     * The LogTimeRangeCursor model constructor.
     * @property {module:model/LogTimeRangeCursor}
     */
    LogTimeRangeCursor,

    /**
     * The LogTimeRangeRequest model constructor.
     * @property {module:model/LogTimeRangeRequest}
     */
    LogTimeRangeRequest,

    /**
     * The LogTimeRangeResult model constructor.
     * @property {module:model/LogTimeRangeResult}
     */
    LogTimeRangeResult,

    /**
     * The NodeChangeEventEventType model constructor.
     * @property {module:model/NodeChangeEventEventType}
     */
    NodeChangeEventEventType,

    /**
     * The ObjectDataSource model constructor.
     * @property {module:model/ObjectDataSource}
     */
    ObjectDataSource,

    /**
     * The ObjectEncryptionMode model constructor.
     * @property {module:model/ObjectEncryptionMode}
     */
    ObjectEncryptionMode,

    /**
     * The ObjectStorageType model constructor.
     * @property {module:model/ObjectStorageType}
     */
    ObjectStorageType,

    /**
     * The ProtobufAny model constructor.
     * @property {module:model/ProtobufAny}
     */
    ProtobufAny,

    /**
     * The ReportsAuditedWorkspace model constructor.
     * @property {module:model/ReportsAuditedWorkspace}
     */
    ReportsAuditedWorkspace,

    /**
     * The ReportsSharedResource model constructor.
     * @property {module:model/ReportsSharedResource}
     */
    ReportsSharedResource,

    /**
     * The ReportsSharedResourceShareType model constructor.
     * @property {module:model/ReportsSharedResourceShareType}
     */
    ReportsSharedResourceShareType,

    /**
     * The ReportsSharedResourcesRequest model constructor.
     * @property {module:model/ReportsSharedResourcesRequest}
     */
    ReportsSharedResourcesRequest,

    /**
     * The ReportsSharedResourcesResponse model constructor.
     * @property {module:model/ReportsSharedResourcesResponse}
     */
    ReportsSharedResourcesResponse,

    /**
     * The RestDeleteResponse model constructor.
     * @property {module:model/RestDeleteResponse}
     */
    RestDeleteResponse,

    /**
     * The RestError model constructor.
     * @property {module:model/RestError}
     */
    RestError,

    /**
     * The RestLogMessageCollection model constructor.
     * @property {module:model/RestLogMessageCollection}
     */
    RestLogMessageCollection,

    /**
     * The RestRevokeResponse model constructor.
     * @property {module:model/RestRevokeResponse}
     */
    RestRevokeResponse,

    /**
     * The RestTimeRangeResultCollection model constructor.
     * @property {module:model/RestTimeRangeResultCollection}
     */
    RestTimeRangeResultCollection,

    /**
     * The ServiceOperationType model constructor.
     * @property {module:model/ServiceOperationType}
     */
    ServiceOperationType,

    /**
     * The ServiceQuery model constructor.
     * @property {module:model/ServiceQuery}
     */
    ServiceQuery,

    /**
     * The ServiceResourcePolicy model constructor.
     * @property {module:model/ServiceResourcePolicy}
     */
    ServiceResourcePolicy,

    /**
     * The ServiceResourcePolicyAction model constructor.
     * @property {module:model/ServiceResourcePolicyAction}
     */
    ServiceResourcePolicyAction,

    /**
     * The ServiceResourcePolicyPolicyEffect model constructor.
     * @property {module:model/ServiceResourcePolicyPolicyEffect}
     */
    ServiceResourcePolicyPolicyEffect,

    /**
     * The ServiceResourcePolicyQuery model constructor.
     * @property {module:model/ServiceResourcePolicyQuery}
     */
    ServiceResourcePolicyQuery,

    /**
     * The TreeChangeLog model constructor.
     * @property {module:model/TreeChangeLog}
     */
    TreeChangeLog,

    /**
     * The TreeNode model constructor.
     * @property {module:model/TreeNode}
     */
    TreeNode,

    /**
     * The TreeNodeChangeEvent model constructor.
     * @property {module:model/TreeNodeChangeEvent}
     */
    TreeNodeChangeEvent,

    /**
     * The TreeNodeType model constructor.
     * @property {module:model/TreeNodeType}
     */
    TreeNodeType,

    /**
     * The TreeVersioningKeepPeriod model constructor.
     * @property {module:model/TreeVersioningKeepPeriod}
     */
    TreeVersioningKeepPeriod,

    /**
     * The TreeVersioningNodeDeletedStrategy model constructor.
     * @property {module:model/TreeVersioningNodeDeletedStrategy}
     */
    TreeVersioningNodeDeletedStrategy,

    /**
     * The TreeVersioningPolicy model constructor.
     * @property {module:model/TreeVersioningPolicy}
     */
    TreeVersioningPolicy,

    /**
     * The TreeWorkspaceRelativePath model constructor.
     * @property {module:model/TreeWorkspaceRelativePath}
     */
    TreeWorkspaceRelativePath,

    /**
    * The AuditDataServiceApi service constructor.
    * @property {module:api/AuditDataServiceApi}
    */
    AuditDataServiceApi,

    /**
    * The EnterpriseConfigServiceApi service constructor.
    * @property {module:api/EnterpriseConfigServiceApi}
    */
    EnterpriseConfigServiceApi,

    /**
    * The EnterpriseFrontendServiceApi service constructor.
    * @property {module:api/EnterpriseFrontendServiceApi}
    */
    EnterpriseFrontendServiceApi,

    /**
    * The EnterpriseLogServiceApi service constructor.
    * @property {module:api/EnterpriseLogServiceApi}
    */
    EnterpriseLogServiceApi,

    /**
    * The EnterprisePolicyServiceApi service constructor.
    * @property {module:api/EnterprisePolicyServiceApi}
    */
    EnterprisePolicyServiceApi,

    /**
    * The EnterpriseTokenServiceApi service constructor.
    * @property {module:api/EnterpriseTokenServiceApi}
    */
    EnterpriseTokenServiceApi,

    /**
    * The LicenseServiceApi service constructor.
    * @property {module:api/LicenseServiceApi}
    */
    LicenseServiceApi,

    /**
    * The SchedulerServiceApi service constructor.
    * @property {module:api/SchedulerServiceApi}
    */
    SchedulerServiceApi
};
